### ISSUE TITLE
Can I can I get the CSI information from multiple APs at the same time if I use injection mode

### ISSUE THREAD

**Issue by chenyongxi** [dhalperi/linux-80211n-csitool-supplementary#10]
Can I can I get the CSI information from multiple APs at the same time if I use injection mode? What are the advantages of the injection mode ？

**Comment by dhalperi** [comment]
If you use injection mode, the receiver can get CSI from all the transmitters. Transmitter is a different thing than AP, however.

**Comment by chenyongxi** [comment]
thankyou! what is transmitter in the injection mode?

**Comment by dhalperi** [comment]
the device you run the transmit code on. Did you look at the injection scripts at all????????????????

**Comment by dhalperi** [comment]
https://github.com/dhalperi/linux-80211n-csitool-supplementary/tree/master/injection 

you run the receiver code on the receiver nodes, and the transmit code on the transmitters. it could literally not be simpler.

**Comment by chenyongxi** [comment]
Sorry，I do not know the principles of the injection mode. I just do what you said . After that I don't know where is transmitters? where I execut the  transmit code? Can you give me some article with the injection mode

**Comment by dhalperi** [comment]
In injection mode, every node involved is a Linux machines running the CSI tool. You designate some of those machines as transmitters and some as receivers.

First put all of the receivers in receiver mode, according to the injection instructions. They will be listening for special packets to measure CSI.

Then put all the transmitters in transmitter mode, according to the injection instructions. Then if you send packets from the transmitters they will be heard by all receivers.

This is, as far as I know, the only way to measure multiple links concurrently.

**Comment by chenyongxi** [comment]
Excuse me, I have a question to ask you. If your environment has multiple AP, how I collect the ap i want.(multiple APs are 80211n and no password )

**Comment by dhalperi** [comment]
associate to that AP and then monitor in normal client mode.
