### ISSUE TITLE
how to work on the 5Ghz in the injection mode 

### ISSUE THREAD

**Issue by ozawali** [dhalperi/linux-80211n-csitool-supplementary#102]
@linkin8834 @dpward @dhalperi   I want to work on the 5GHZ in the injection mode, so  I set the rate_flage of the 40MHZ 0x800 and then I setup the paramter 64 HT40-.  I want to know how to confirm i setup successed. Meanwhile I want to know the mean of two paramter-channel number  Band. why there is HT40- or HT40+ but the the HT40.  another qunstion is  that in the FAQ#2  the example perm of csi   the antenna C,B,A whether is the antenna 3,2,1 on the mark on the NIC that the sequence is 1,3,2 in the picture on the main page  Thank you

**Comment by dhalperi** [comment]
I'm a bit confused by this question, can you separate it out better? Here's my guess, however.

1. 40 MHz channels are defined by pairing two 20MHz channels: a control channel and an extension channel. When we say "64 HT40-" that is two separate arguments. The first says "use channel 64 as the control channel". The second says "use a 40 MHz channel with the extension channel below the control channel". This means, therefore, the 40 MHz channel consisting of {64, 60}.

2. The markings on the NIC do indeed show that antenna 1/A, 3/C, and 2/B are places on the board in that order. However, that order has nothing to do with the `perm` field -- that is the order in which antennas were mapped to RX chains. A `perm` of [3,2,1] means that antenna 3/C was sent to RX chain 1, 2/B to RX chain 2, and 1/A to RX chain 3, and these are the orders they show up in the RX dimension of the CSI. Thus we have to undo this permutation to get the actual CSI where antennas are consistent.
