### ISSUE TITLE
Known problems with CSI measurements in firmware

### ISSUE THREAD

**Issue by chaloz** [dhalperi/linux-80211n-csitool-supplementary#104]
Dear all,

is there any comment/discussion that summarises all known problems with measurement of the channel transfer function, such as the one reported in #6, or can someone forward me to a paper that reported any issues with the signal processing in the firmware?

Anyway, such information would be very helpful in the FAQ of the main page of the csitool.

Thank you and regards
Zdenek

**Comment by dhalperi** [comment]
Happy to take a pull request! Unfortunately I have not actively worked with this tool in over 4 years, so am not able to make these types of improvements.
