### ISSUE TITLE
phase difference between RX chains is not constant, pls help!

### ISSUE THREAD

**Issue by hotdrive** [dhalperi/linux-80211n-csitool-supplementary#111]
we are doing some AoA localization research on 5300 NIC, when calibrate the initial phase of 3 RX chains, We find : phase difference between RX chains is not constant, it varies like a noise.
our calibration method: use NIC(A) as a TX, connected with a cable and a splitter, the 2 output of splitter connect to 2 RX ports of NIC(B).
I am wondering if the 3 RX chains shares the same clock, the phase difference between RX chains in the same time should be constant?

**Comment by hotdrive** [comment]
We also find ,the AGC in the packets is also changing ,will AGC results in the problems?

**Comment by hotdrive** [comment]
by the way, the variation is about 10~40 degrees

**Comment by dhalperi** [comment]
The [Phaser](https://jon.thesquareplanet.com/papers/mobicom14-phaser.pdf) project found that phase difference between RX chains was only constant at 5 GHz band.

I assume you're looking at CSI output by `get_scaled_csi`, right, not raw? Otherwise you'll get strange receiver antenna selection effects.

And you're hard-coding both the transmit rate and a single transmit antenna, for good measure?

**Comment by ozawali** [comment]
@dhalperi  you mean that cannot use the get_scaled_csi ?

**Comment by hotdrive** [comment]
@dhalperi,thx for your reply.
1)we already known this problem, so we are using 5GHz band; monitor mode; single transmit antenna
2)I also noticed the antenna selection effects and correct it. It seems the phase difference will not change by using raw CSI or CSI output by  get_scaled_csi .
BTW, what is the right variation of the channel phase difference if power on? 10 degrees? what makes the variation?
Look foward to your reply.

**Comment by dhalperi** [comment]
Others have made this work; I suspect your setup has something wrong. You
might ask them, though!

**Comment by hotdrive** [comment]
@dhalperi
Will AGC impact the phase? we find that AGC varies in packets.
BTW, which teams have made this work? any paper ? I have read a lot papers, but the answer is the phase difference is constant without any explain.
I also suspect the setup problem.

**Comment by dhalperi** [comment]
I already linked a paper: https://github.com/dhalperi/linux-80211n-csitool-supplementary/issues/111#issuecomment-149776936
