### ISSUE TITLE
Relative phase between 2 rx antennas will shift pi or  pi/2

### ISSUE THREAD

**Issue by libing64** [dhalperi/linux-80211n-csitool-supplementary#113]
I am using a NIC card as a transmitter and another NIC as a receiver, and I plot the relative phase between rx antenna 1,2 and between antenna 2,3. 
plot(angle(antenna1 .* conj(antenna2))) 
plot(angle(antenna2 .* conj(antenna3))) 

Sometimes the relative phase will shift pi or pi/2.
@dhalperi @dpward @ippeb @xu-wang11
can anyone give me some advice to figure it out or solve this problem?

![screenshot from 2015-10-25 23_45_13](https://cloud.githubusercontent.com/assets/3192355/10719496/ac698cb8-7bc4-11e5-81dc-a5b78831c8f0.png)
![screenshot from 2015-10-25 23_44_44](https://cloud.githubusercontent.com/assets/3192355/10719497/ac6c132a-7bc4-11e5-9290-67c07ce7c11b.png)
![screenshot from 2015-10-25 23_44_09](https://cloud.githubusercontent.com/assets/3192355/10719498/ac6e4226-7bc4-11e5-991a-84b7965e7449.png)
![screenshot from 2015-10-25 23_43_15](https://cloud.githubusercontent.com/assets/3192355/10719499/ac6fef40-7bc4-11e5-8a26-ef574f8eff23.png)
![screenshot from 2015-10-25 23_42_19](https://cloud.githubusercontent.com/assets/3192355/10719500/ac72df52-7bc4-11e5-901f-81d58eea4c45.png)

![screenshot from 2015-10-25 23_41_16](https://cloud.githubusercontent.com/assets/3192355/10719501/ac92be94-7bc4-11e5-9df1-c1875f301e69.png)

**Comment by ozawali** [comment]
you do this job on the 2.4G or 5G?

**Comment by ozawali** [comment]
on the 5G I haven't this problem and it is the constant

**Comment by libing64** [comment]
This is the configuration command：    
transmitter configuration:
        ./setup_inject.sh 64 HT20
         echo 0x4101 | sudo tee `find /sys -name monitor_tx_rate`
         sudo ./random_packets 100000 100 1 1000
 
     receiver configuration:
         ./setup_monitor_csi.sh 64 HT20

I think the frequency of channel 64 is 5.32GHz.
Is the configuration right? @ozawali

**Comment by ozawali** [comment]
how to receive ? splitter?

**Comment by libing64** [comment]
I receive the package with log_to_file, and plot it with in ros.
What you mean by splitter? Sorry I don't get the point. @ozawali

**Comment by ozawali** [comment]
你所看到的相位差是你直接用空中传输得到的吗？ 如果是那样相位差不可能恒定

**Comment by libing64** [comment]
The phase is not constant but the relative phase between 2 rx antennas should be constant if they are kept static.  @ozawali

**Comment by libing64** [comment]
I think I have solved this problem.
According to issue [#6] (https://github.com/dhalperi/linux-80211n-csitool-supplementary/issues/6) 
On 2.4 GHz bands, it appears that each antenna experiences an unknown phase shift by a multiple of π/2 (or 90 degrees). 

Through I have configured the channel, it seems doesn't work.
When I verify the configuration with 
      #iwconfg
The frequency is still 2.4G.
After configure the channel with iwconfig
     #iwconfig wlan0 channel 64
the frequency becomes 5G, then the shift disappears.

**Comment by libing64** [comment]
Thanks @ozawali  and @xu-wang11 for your kindly help.

**Comment by libing64** [comment]
@dhalperi @dpward , Now you can close the issue, thanks.

**Comment by snowyy2019** [comment]
@libing64 
#iwconfig wlan0 channel 64 
Can you tell me this command is executed in recevier or transimitter?

**Comment by libing64** [comment]
@shaozhuchuang  the both.

**Comment by snowyy2019** [comment]
@libing64 I also do an experiment and collect some csi information, but i found the data is very not stable, I don't know whether my data and my matlab code have some problems, Can you send your csi files and relate matlab code to me, My email is shaozhuchuang@126.com or mrshao@sjtu.edu.cn. if you are inconvenient to send matlab code to me, i hope you can only send csi files. Thank you!

**Comment by ziqihuang233** [comment]
@libing64 @ozawali Sorry to bother you both. I try to  plot the relative phase between rx antenna 1,2 and between antenna 2,3. And the result is constant which is 0. Am I right？ I use AP as transmitter and NIC as receiver. And I work in 5G 20MHZ. 
![relativephase0](https://cloud.githubusercontent.com/assets/16526692/18498147/db2d10dc-7a66-11e6-803f-461498cf462a.jpg)
