### ISSUE TITLE
another question: about the csi_trace 

### ISSUE THREAD

**Issue by haimapi** [dhalperi/linux-80211n-csitool-supplementary#115]
Thanks for help, and I've open the struct, e.g the 43rd struct, it's empty.
![qq 20151104114126](https://cloud.githubusercontent.com/assets/15070162/10928998/00f334fc-82e9-11e5-977d-db8a1841129a.png)

**Comment by dhalperi** [comment]
Please post the actual interpreter command line and output -- these screenshots are not useful.

Note that `csi_trace{43,1}` is not correct -- it should just be e.g. `csi_trace{43}`.

**Comment by dhalperi** [comment]
Also in your second screenshot from #114, `csi_trace{43}` is an empty cell -- only 1 through 42 are valid.

**Comment by haimapi** [comment]
I tried to get the CSI:

>> csi_entry=csi_trace{43}

csi_entry =

     []

>> csi=get_scaled_csi(csi_entry)
??? Attempt to reference field of non-structure array.

Error in ==> get_scaled_csi at 7

**Comment by haimapi** [comment]
Actuall I make MP ping to the AP for about 1min to get this .dat file. I just feel puzzled that only 42 structures were alivable in a .dat file..

**Comment by ozawali** [comment]
you should see the clue the system show you that if you receive the packets.

**Comment by ozawali** [comment]
see the all FAQ

**Comment by dhalperi** [comment]
If your question is why you aren't receiving packets, please carefully read the [FAQ](http://dhalperi.github.io/linux-80211n-csitool/faq.html), especially number 6.
