### ISSUE TITLE
relative phase is not right?

### ISSUE THREAD

**Issue by libing64** [dhalperi/linux-80211n-csitool-supplementary#124]
I want to do some experiments following this paper, “Accurate indoor localization with zero start-up cost”
http://dl.acm.org/citation.cfm?id=2639142
According to this paper, the relative phase between 2 rx antennas should be 
relative_phase = 2*pi \* r/lambda  \* cos(alpha)
r is the distance between two rx antennas
lambda is the wave length of the wifi signal
alpha is the relative angle between the antenna array direction and the wifi signal direction.

I have tested the relative phase with only two antennas, it is right and the result just like the math model.
# 

However, if I use 3 antennas for receiving, (1 2 3 as a linear array, so the relative phase between 1 and 2,  2 and  3 should be the same in theory ) , the relative phase between 1 and 2 is really different with  the relative phase between 2 and 3.

![relative_phase00022](https://cloud.githubusercontent.com/assets/3192355/11477501/45a66da0-97c3-11e5-8448-052d4e575520.png)

![relative_phase1](https://cloud.githubusercontent.com/assets/3192355/11477529/640a354c-97c3-11e5-8339-1bfb3b063297.png)

**Comment by libing64** [comment]
5GHz, injection mode, outdoor environment
1 tx antenna
3 rx antennas

**Comment by libing64** [comment]
@dhalperi @dpward @ippeb @xu-wang11
Do you have any idea about this problem? Great thanks for your kind help.

**Comment by dpward** [comment]
I noticed the same behavior you did in trying to extend that work as well. In discussions with the authors of that paper, they believed (as I mentioned in #122) that crosstalk was at least partially causing the phase difference when taking measurements from the antenna.

**Comment by libing64** [comment]
Do you know how to remove the crosstalk? @dpward

**Comment by libing64** [comment]
@dpward
I don't think it's caused by crosstalk. 
According to wiki, "In wireless communication, crosstalk is often denoted co-channel interference, and is related to adjacent-channel interference"
"Co-channel interference or CCI is crosstalk from two different radio transmitters using the same frequency."

If it is caused by crosstalk, the relative phase will also be affected when I use only two rx antennas. However, when I use only two rx antennas, the relative phase really follows the math model.

x-axis: yaw angle
y-axis: relative phase
Collected data and the math model
![screenshot from 2015-11-17 18_24_01](https://cloud.githubusercontent.com/assets/3192355/11492316/613f3520-9826-11e5-8f70-20dd74d5455f.png)
![screenshot from 2015-11-17 18_31_11](https://cloud.githubusercontent.com/assets/3192355/11492317/614cd8ce-9826-11e5-9781-3287a6a4df29.png)

**Comment by dpward** [comment]
@libing64 I was referring to crosstalk in the adapter itself, not wireless communication crosstalk. It's described on [Wikipedia](https://en.wikipedia.org/wiki/Crosstalk_%28electronics%29) (right below wireless channel crosstalk):

"In [integrated circuit design](https://en.wikipedia.org/wiki/Integrated_circuit_design), crosstalk normally refers to a signal affecting another nearby signal. Usually the coupling is capacitive, and to the nearest neighbor, but other forms of coupling and effects on signal further away are sometimes important, especially in analog designs. See [signal integrity](https://en.wikipedia.org/wiki/Signal_integrity) for tools used to measure and prevent this problem, and [substrate coupling](https://en.wikipedia.org/wiki/Substrate_coupling) for a discussion of crosstalk conveyed through the [integrated circuit substrate](https://en.wikipedia.org/wiki/Integrated_circuit). There are a wide variety of possible fixes, with increased spacing, wire re-ordering, and shielding being the most common."

Unfortunately, beyond attempting to shield the antenna wiring especially over the connectors themselves (which didn't help as far as I could tell), the "fixes" are to change the integrated circuit design of the adapter.

**Comment by libing64** [comment]
@dpward Great thanks.
I find that the relative phase in this paper  "SpotFi: Decimeter Level Localization Using WiFi" is not the same too.  Maybe this paper has solved this problem.
I will try the method used in this paper. 
![qq 20151201225938](https://cloud.githubusercontent.com/assets/3192355/11504318/afbe054c-987f-11e5-945a-1dac82d3925d.png)

**Comment by lixiaohai** [comment]
@libing64 
hello!I am also donging some experiment on relative phase.I find that the relative phase  you get change 2pi at some points,it's just like mine.Do you know whether it's normal ?or do I have used the wrong method to get the relative phase?here is one of my data:


![image](https://cloud.githubusercontent.com/assets/9332643/11585050/02186e88-9aa4-11e5-9694-884d6113b174.png)

**Comment by lixiaohai** [comment]
@libing64 
hello!I am also donging some experiment on relative phase.I find that the relative phase  you get change 2pi at some points,it's just like mine.Do you know whether it's normal ?or do I have used the wrong method to get the relative phase?here is one of my data:
![image](https://cloud.githubusercontent.com/assets/9332643/11585076/30073ff4-9aa4-11e5-8529-fc53226b0ab4.png)

**Comment by libing64** [comment]
@lixiaohai I think it is normal to change 2*pi, because alpha and alpha+k \* 2 *pi is the same angle.

**Comment by lixiaohai** [comment]
Much appreciation for your kind reply!!

**Comment by lidongmeng** [comment]
@libing64 hello, I am wondering if u can reimplement the method "SpotFi: Decimeter Level Localization Using WiFi", recently I am reading this paper, but I have lots of question, can u  help me.

**Comment by libing64** [comment]
@lidongmeng sorry, I cannot reimplement that method. I once tried that method, but it didn't work on my dataset.

**Comment by snowyy2019** [comment]
@libing64  I also do an experiment and collect some csi information, but i found the data is very not stable, I don't know whether my data and my matlab code have some problems, Can you send your csi  files and relate matlab code to me, My email is shaozhuchuang@126.com or mrshao@sjtu.edu.cn. Thank you!

**Comment by egaebel** [comment]
It seems that many of us are interested in SpotFi. @libing64 were you able to correctly implement Algorithm1 from the SpotFi paper to remove the offset from sampling time? It seems straightforward, but my implementation does not give results similar to the one from the paper. Specifically, my phase is not transformed to look like this figure: 

![screenshot](https://cloud.githubusercontent.com/assets/2490298/13831202/453a1b9e-eba8-11e5-9e5d-cd1c6f918a81.png)

It stays looking like this, although there are noticeable shifts in the phases from antenna 2.

![screenshot2](https://cloud.githubusercontent.com/assets/2490298/13831217/658e51d0-eba8-11e5-9a2b-f039ccedb0df.png)

**Comment by libing64** [comment]
@egaebel It's very simple to remove the phase offset.
Look at the phase picture,  and if you add some codes like this, 
if( (phase_current - phase_prev) > pi \* 1.5 ) phase_current -= 2_pi
if( (phase_current - phase_prev) < -pi \* 1.5 ) phase_current += 2_pi
then it will be similar to the figure from SpotFi. 
![relative_phase00022](https://cloud.githubusercontent.com/assets/3192355/11477501/45a66da0-97c3-11e5-8448-052d4e575520.png)

**Comment by egaebel** [comment]
@libing64 wait, how does that implement SpotFi's sanitization algorithm?

![screenshot-algo-1](https://cloud.githubusercontent.com/assets/2490298/13833926/ddfc8f5c-ebc0-11e5-9b2d-41126dd0f3ca.png)

**Comment by libing64** [comment]
@egaebel It's just a simple line fitting, assume that phase  = a_t + b
then the phase without offset is phase_without_offset = phase - a_t

**Comment by egaebel** [comment]
@libing64 Just to be clear, is phase_prev the phase of the previous subcarrier on the same packet, or the phase of the same subcarrier on the previous packet?

Thank you so much for helping me with this.

**Comment by libing64** [comment]
@egaebel 
It is the phase of the same subcarrier on the previous packet

**Comment by cedivad** [comment]
@libing64, sorry for bothering you, but I'm asking since that it looks like you understood it. What is beta in the first formula of the first algorithm for spotifi? I think I got pretty close to have it working, but only when I multiply the STO by say 2 to 3 before using it to correct the phase. I believe it's because I didn't use beta in the formula searching for STO, because I didn't knew what to put in.

I belive it must be something so evident to everyone (but me) the authors didn't even bother specifying. 

Thank you.

**Comment by snowyy2019** [comment]
@egaebel Are you implement SpotFi's sanitization algorithm? I don't know how to do about this algorithm. can you help me? thank you!

**Comment by snowyy2019** [comment]
@libing64 I found we can get unwrapped phase bu using unwrap command in matlab, I don't know the difference with you method mentioned above, can you help me about your method get unwrapped phase. i need your help.thank you!
this picture is untwapped phase, this phase is different with spotfi. i don't konw the reason
![picture1](https://cloud.githubusercontent.com/assets/5352010/14600316/7ff74bf8-058e-11e6-9c15-78a6c1daa3fd.jpg)

**Comment by libing64** [comment]
@shaozhuchuang  It seems same as SpotFI. What you mean by "this phase is different with spotf“?

**Comment by snowyy2019** [comment]
@libing64  According to spotfi, the phase difference of different packages is bigger than the phase difference of different antenna using the same package, but i don't find it in my picture.

**Comment by libing64** [comment]
@shaozhuchuang Please note that the phase difference between two antennas is related to the distance between two antennas and the wavelength of the wifi signal.

**Comment by asifhanif1122** [comment]
@libing64 Can you kindly explain SpotFi's alogorithm-1 . I am unable to understand it. Especially the terms used in it. Ro and veeta . Which parameters are they corresponding to? 

![a1](https://cloud.githubusercontent.com/assets/15953476/14633089/7133f272-0635-11e6-88b7-aab28493c7ee.PNG)

**Comment by cedivad** [comment]
p is the term you need to minimise (arg min of p), I think you can leave B at zero.

**Comment by egaebel** [comment]
p (rho) and B (beta) are terms of a linear fit.

**Comment by cedivad** [comment]
@egaebel I'm guessing, p is the slope, B the intercept? I looked at the Wikipedia page for the beta parameter before but I really couldn't get it, so I kept it to zero and my results weren't that bad (I couldn't get past the most basic MUSIC graph, but I was expecting that). I really regret lacking basic math skills here.

**Comment by egaebel** [comment]
Yep. You got it. Just dig through the math and keep digging until you understand. I had to do the same thing several months ago. It all clicks eventually :).

**Comment by snowyy2019** [comment]
@cedivad @egaebel Are you implement SpotFi's sanitization algorithm? can you share it with me . I have studied for a long time. Thank you!

**Comment by libing64** [comment]
@shaozhuchuang I tried to implement the algorithm in SpotFi several month's ago, but it doesn't work. Please note the evaluation in SpotFi. It seems that  it doesn't works much better than general MUSIC algorithm for AoA estimation.
SpotFi’s accuracy stems from two key components. First is its super-resolution AoA estimation algorithm whose
**median error is less than 5 degrees in LoS conditions and less than 10 degrees in NLoS conditions. The MUSIC al- gorithm used in practical implementation of ArrayTrack only achieves an estimation error of 7.4 and 15.2 degrees respectively for the same scenarios**. Second, SpotFi’s likelihood estimation algorithm ensures that among the available estimates, incorrect estimates for the direct path are likely not picked, and even if they are, they will be weighted with low confidence and have a lesser impact on the location estimate

**Comment by snowyy2019** [comment]
@libing64 thank you for your reply! Are you implement super-resolution AoA estimation algorithm? i only know how to implement basic music algorithm to calculate AoA , and i don't know how to combine AoA and ToF in music algorithm. besides,i don't use subcarrier information to calculate AoA. Can you give me some instructions? Thank you!

**Comment by MBrend15** [comment]
Great comments on SpotFi! 

This is more of a MATLAB specific question. How does one calculate regression over all antennas/subcarrier? Basically I used the mvregress command (below, b is a 1x30 column vector of values, from 1-30, for x values, then phase_mat is a 3x30 array) and then took the average of the three returned coefficients (Each coefficient only represented a regression over a single antenna). This returns a workable result but I know this is not the most accurate way to find best fit over values of each antenna and sub-carrier. 

y = mean(mvregress(b,phase_mat));

Thanks for the help!

**Comment by egaebel** [comment]
I have also implemented SpotFi, although only from a single point, there is no result fusion between access points. I've found it to perform pretty well, although not quite as well as I had expected. I can post my code here once I open it up to the public in 2-3 weeks.

**Comment by egaebel** [comment]
@shaozhuchuang I had to read the SpotFi paper many, many times before I could properly understand how to combine ToF and AoA in MUSIC. Examine their construction in figure 3. Then examine it over and over again until it makes sense :). It's important to understand that MUSIC works on sensors, not antennas. What the authors of SpotFi demonstrate in Figure 3 is how to reconstruct the ToF and AoA data obtained from antennas into many sensors.

![spotfi-figure-3](https://cloud.githubusercontent.com/assets/2490298/14749648/b14f65fc-088e-11e6-9364-82d681bd3b02.png)

**Comment by libing64** [comment]
@egaebel  Good new that someone successfully implement SpotFi algorithm. I once tried to re-implement SpotFi, but it didn't work with my own data(indoor environment).   (Maybe there are some bugs in my code)

Are you using Intel 5300 NIC or Atheros NIC for collecting CSI data? 
Is the data collected indoor or outdoor?

**Comment by snowyy2019** [comment]
@egaebel  Great!! I',m so happy to konw your implemention, Looking forward for your code and result! I think it can help me greatly!  Thank you!

**Comment by dongxinb** [comment]
@egaebel @libing64 

Sorry to be a bother. These days I'm trying to implement the SpotFi and here is a question about CSI Smoothing.
As shown in the image, the size of the matrix is (30_30). But the actual size in this matrix is (30_32) because there are 32 columns and 30 rows. 
I'm not sure this is just a typo or something else. Could you give me some instructions?
Thanks a lot!

<img width="559" alt="screen shot 2016-04-26 at 2 30 39 am" src="https://cloud.githubusercontent.com/assets/5591515/14794475/ebda21b0-0b56-11e6-9bf6-8fc5757d8c0a.png">

**Comment by egaebel** [comment]
@dongxinb 

No problem! I actually e-mailed the authors about this and they told me that the matrix is 30x32. The 30x30 indication is a typo.

**Comment by egaebel** [comment]
@libing64 I'm using the Intel 5300 NIC with indoor data. I was going to gather outdoor data too (and probably will eventually) but I've been strapped for time. I'm running SpotFi from a single access point so I'm only obtaining the angle of arrival and it is only from the one point, there's no results fusion. My results are not too bad. I find that it's more useful to look at the results in terms of top-5 accuracy because of the likelihood selection method. Oftentimes the wrong cluster is selected, but not by much. From 1m away I get 100% top-4 accuracy.

I'm using this technique for my masters thesis, I can post a final paper here covering it when I'm all done :).

**Comment by libing64** [comment]
@egaebel Great thanks for your reply.
I will pay more time to debug my code.

**Comment by dongxinb** [comment]
@egaebel 
Thank you for you kind reply.
I'll tell my thoughts below and could you please evaluate if my thought is correct?
1. Collect the data from csitool and get the matrix.
2. Use the Algorithm 1 to sanitize the ToF estimates. 
   2.1 I convert the complex to angle and module, and remove the periodic effect. (Make the points look like a line rather than periodic polyline).
   2.2 Get the linear fitting result(y-axis is phase, x-axis is different subcarriers in one packet), the slope is p. Then new_phase_of_subcarrier_i=phase_original_of_subcarrier_i - i \* p.
   2.3 Using the new phase and reconstruct the csi_data_matrix.
3. Construct the smoothing matrix using the new csi_data_matrix. The size is 30x32.
   3.1 Using the matlab function "pmusic(matrix, 30)" to get the result: s, w.
   3.2 Find the max(s) and its index, then w(index) is the unknown angle.

Besides, could you share your csi_data file and the real angle(if possible)? I think my data might have some problems, and I cannot capture new data these days.
Thanks again!

**Comment by plank3ffect** [comment]
@egaebel @dongxinb ,

My understanding on the MUSIC algorithm is that you really have to write your own according to the mathematical model presented as a combination of RSSI_MN = Phi_theta_k^M \* Omega_tao_k^N  (Eqn 1 x Eqn 6).  

@egaebel
How exactly did you implement the MUSIC algorithm?  Did you create a separate MUSIC algorithm problem for each path, set up similar to Figure 3b?  Or did you somehow operate on the entire [30x32] smoothing matrix?  My thoughts are that for every path, you have to model the following:
[choose two 30x1 subarrays to compare] = [corresponding 30x2 steering] x [2x2 independent vector of gains].  Any help or comments on your approach would be greatly appreciated.

@dongxinb, I found this website really helpful in understanding composing the MUSIC algorithm!
http://www.edaboard.com/thread79938.html

**Comment by egaebel** [comment]
@dongxinb @plank3ffect 

You need to roll your own MUSIC implementation. pmusic in matlab is not equipped to handle time of flight. SpotFi builds directly on top of MUSIC, fundamentally altering it so to be able to do this you need your own implementation.

@plank3ffect 
I'm not quite certain what you mean by "a separate MUSIC algorithm problem for each path." Figure 3b is a much smaller explanation of how to construct the smoothed CSI matrix in general. The authors move certain terms into the matrix F from music so that the matrix A can be constructed to only be made up of steering vectors. It's sort of like a matrix factorization, but a very creative one. 

The 30 x 32 smoothed matrix is the signal matrix that is input to MUSIC. You find its eigenvectors and construct E_{N} which is finally multiplied with the steering vector in the music peaks equation P_{MUSIC}(\theta, \tau) = 1 / a^{H}(\theta, \tau) E_{N} E^{H}_{N} a(\theta, \tau).

Figure 3b is purely for explanatory purposes.

This paper was crucial to my understanding of MUSIC: http://www.diva-portal.org/smash/get/diva2:724272/FULLTEXT01.pdf

**Comment by plank3ffect** [comment]
@egaebel ,
Thanks for the feedback!  Can you shed some light on your search space with only the single smoothed matrix as the objective measurement matrix?  My intuition is that one would have to search through (\theta_{k},\tau_{k}) with k \in [1,5].  In other words, an optimization problem with 10 variables,  \theta and \tau for each path, assuming five paths.  That would take a long time! (right?)

**Comment by egaebel** [comment]
@plank3ffect 
You could make this an optimization problem I suppose....or you can just plug in combinations of values for\ tau and \theta based off of what we know. For angle of arrival I try every angle from -90 to 90 and for time of flight I use...I think microsecond granularity and go up to a few hundred microseconds. I'll double check this later, but the point is that treating this as an optimization problem from the outset without using the prior information we have about the problem is not a good starting point.

Plugging in values takes a while, but not that long. On top of this it's a highly parallelizable problem. If you're that worried about performance you should look at Matlab's parfor loop.

**Comment by plank3ffect** [comment]
@egaebel,

I think we are getting to the same page of understanding.  I have it set up to search every angle for AoA and time for ToF, but that would only return a solution for only one path.  From what I gather, each path has a different AoA and ToF.   The SpotFi paper mentions they analyzed for five paths, and it seems the smooth matrix then incorporates all paths (so you would have to solve for 10 variables at once).  That's what threw me off.  Were you able to extract the variable pairs (AoA, ToF)_path1, (AoA, ToF)_path2, (AoA, ToF)_path3, (AoA, ToF)_path4, (AoA, ToF)_path5 from a single CSI matrix?   I take it that mean you swept through 10 variables over this one matrix?  Trying to see if I'm framing this right for five paths.  Or did you only solve for one path?  THanks!

**Comment by egaebel** [comment]
@plank3ffect 

You should get as many peaks in the music spectrum as there are paths. So if there are 5 paths then you should expect to see 5 peaks in the music power spectrum. Ideally, the largest of these will be the direct path. Those peaks will correspond to particular angle of arrival and time of flight inputs. There's variability though, which is why the SpotFi authors compute this for each packet and then cluster all the packets.

**Comment by snowyy2019** [comment]
@egaebel Are you know how to get the likelihood of each cluster, please tell me if you know about it.Thank you!

**Comment by ColdCodeCool** [comment]
@shaozhuchuang  Hi, there! I recognized you are from SJTU,  so we are both in Shanghai. I am a first year Ph.d student in the newly built ShanghaiTech.  I've sent you an email to your school mailbox, please check it, hope to talk with you soon!!
Regards

**Comment by MBrend15** [comment]
@shaozhuchuang 

The authors of the paper indicated that to determine likelihood score, you have to weigh your variation of AoA, ToF, number of packets per cluster, and average ToF with weight values but they do not include the weights in the work. I took that to mean that they can be arbitrary and chose values that returned a reasonable likelihood score per cluster (usually between 1 or 2). Obviously this is my interpretation and I would be interested to get the group's opinion.

**Comment by egaebel** [comment]
I'm not sure how the authors actually determined the likelihood weights.

I used a linear SVM on labeled data to determine them.

**Comment by egaebel** [comment]
As promised, here is a link to my SpotFi implementation:

https://github.com/egaebel/lgtm/tree/master/csi-code

In case the links change in the future the master project is here:

https://github.com/egaebel/lgtm/

**Comment by ColdCodeCool** [comment]
@egaebel  I got a naive question here, how should we obtain the ground truth incident angles of the antenna arrays?  More accurately, we should choose whether the horizontal direction or vertical direction of the antenna arrays as the reference direction to construct the incident angle,  or neither.

Thank you in advance!

**Comment by elegance0222** [comment]
@egaebel 
Hello, thank you for sharing your code for us, first. I have issues about CSI data collection.

When I follow to reimplement SpotFI, I confused that the CSI data collection form both receiver and transmitter must be with Intel 5300. 

The issue is that whether to make 5300 NIC in injection mode to get CSI data for phase processing, or with hostaapd? other AP is OK? How do you get the CSI data? Thank you a million.

**Comment by egaebel** [comment]
@ColdCodeCool
Use the horizontal direction, the long one that is.

@lingyan0222 
You should be able to get CSI data in, I think, any of the modes. For SpotFi I used injection mode since my particular application was better suited for it. Only way to figure it out for yourself is to dive in and try.

**Comment by elegance0222** [comment]
@egaebel 
Thank you for your prompt feedback. I will try it.

**Comment by ColdCodeCool** [comment]
@egaebel 
Thank you for your kind reply.

In your code, at the sanitization part, I think fit_X(1:30,1) = 0:1:29, and so are fit_X(31:60,1),fit_X(61:90,1).

And fit_X = -fit_X \* 2 \* pi \* delta_f;

Then the polyfit will do it right.  And the modified CSI phase is just look like that in the SpotFi paper. 
Do you agree with me?

**Comment by libing64** [comment]
@egaebel 
I compared the logged data from you and me, it seems that the phase of the third antenna is right in your data but not in my logged data.
This is the from your logged file. Note that the relative phases really fit the math model.
![los-test-desk-left dat_1](https://cloud.githubusercontent.com/assets/3192355/15535640/cf1d7fb6-22a0-11e6-863d-a6c5973b9f3b.png)

This is from my logged data.
![csi_outdoor txt_5](https://cloud.githubusercontent.com/assets/3192355/15535692/fa6a42a8-22a0-11e6-90af-99f96a2120fe.png)

In my experiment, when I uses two antennas, the relative phase fits the math model well, but when I use three antennas, the phase from the third antenna is always very strange. 
Are you using injection/monitor mode or others? Can you show me your configure file at transmitter and receiver? Great thanks.

**Comment by libing64** [comment]
@egaebel  I have found your configure file in your lgtm repo. I will try that on my platform.

**Comment by lingyan0222** [comment]
@egaebel 

On collecting 40MHz csi data, which monitor_tx_rate to set? 0x4101 or 0x4801?

the receiver:
**./setup_monitor_csi.sh 64 HT40-**

the transmitter 
**./setup_inject.sh 64 HT40-**

**Comment by lingyan0222** [comment]
Hi @egaebel 

Using injection mode to collect 40MHz CSI data form 5GHz, the parameters is HT64+ or HT64- for the CSI signal form 60-64 channel? Thank you.

**Comment by hot-dog** [comment]
@libing64 @dpward @lidongmeng @shaozhuchuang @lixiaohai Hi, I am wondering why the unwrapped CSI phase is nearly liner, can you tell me the reason or give me some materials related? Thanks!

**Comment by stfremont** [comment]
it is linear when the client and the ap are very close. basically no multipath effect or tof/tone impact.

**Comment by milindmathai** [comment]
@egaebel can you please explain your implementation of algorithm 1, I have spent alot of time on it and havnt figured it out. My email id is mldmathai@gmail.com. Thank you so much

**Comment by milindmathai** [comment]
@egaebel can you please explain your implementation of algorithm 1, I have spent alot of time on it and havnt figured it out. My email id is mldmathai@gmail.com. Thank you so much

**Comment by milindmathai** [comment]
@egaebel Hi, thank you so much for sharing your code. I didnt understand a part of algorithm 1, ie, i didnt understand what fit x and fit y are? and why have you defined fit y the way you have. I have spent alot of time on this and have not been able to figure this out. My email id is mldmathai@gmail.com. Thank you so much

**Comment by milindmathai** [comment]
@egaebel Hi thank you so much for your code. I didnt understand how you implemented the music algorithm however. Why did you need to find the ratio? Couldnt you have just arranged the eigenvalues in ascending order and used the M-D eigenvectors in ascending order? Thanks, my email ID is Milind Mathai

**Comment by milindmathai** [comment]
@egaebel Hi thank you so much for your code. I didnt understand how you implemented the music algorithm however. Why did you need to find the ratio? Couldnt you have just arranged the eigenvalues in ascending order and used the M-D eigenvectors in ascending order? Thanks, my email ID is mldmathai@gmail.com

**Comment by zhangdh24** [comment]
@libing64  I have the same problem as you do, when I try SpotFi, but the data logged by @egaebel  does not have such problem. Have you found out what cause the problem? Thanks a lot.

**Comment by saltdou** [comment]
@libing64 I also met the different relative phase difference among the antennas. Have you solve this problem? What is your configuration about the Tx and Rx? Thanks

**Comment by zhangdh24** [comment]
@saltdou I have tested @egaebel 's code, it seems that some of his data has the same problem, which make the estimation not accurate. I have tried to calibrate the phase but it doesn't work.

**Comment by saltdou** [comment]
@zhangdh24 Did you try his configuration? I found  the datarate sometimes fluctuates a lot.

**Comment by zhangdh24** [comment]
@saltdou  Not yet. Because I find out that the performance reported in his paper seems to be too bad, compared with SpotFi. I am still trying to find out what cause the problem

**Comment by saltdou** [comment]
Thanks for ur updates. Please let me know if you have any new find-out.

**Comment by zhangdh24** [comment]
@saltdou  I guess that the relative phase error is normal because the model of linear array for wifi signal is not precise in the indoor environment. The Fig.5 b shows the CSI phase on three antennas, the relative phase seems not to be right, either. However, if you can still try to calculate AOA in this case, because I find out that sometimes the relative phase is right for two antennas( it is random in my experiment). Thus, if you have thousands of packets, you can still get an estimation of AOA. Although SpotFi claims that the median accuracy is about 40cm, the density of APs used in the experiment is quite large, which will increase the localization accuracy greatly.

**Comment by saltdou** [comment]
@zhangdh24 Many thanks for your explanation. You can see my plot without process. The relative phase seems to have an unexpected multiple pi/2 shift at 2.4 GHz. Did you meet this case?

![image](https://user-images.githubusercontent.com/27623433/33970209-bf9b8562-e0ac-11e7-8e17-e7b04875fe8b.png)

**Comment by zhangdh24** [comment]
@saltdou It caused by the inherent limitation on 2.4GHz which has been reported by previous papers， you need to use 5GHz if you want to get a stable phase difference between antennas.

**Comment by saltdou** [comment]
Yeah. I have seen some paper talking about this phenomenon. I wonder if
somebody solved this problem.
Thanks for your sharing.

**Comment by saltdou** [comment]
Unlucky, I also met this problem at 5 GHz, but it changes not that fast.
There is a pi/2 phase shift after several seconds. Could you tell me the
specific configuration of your platform？
Many thanks.

**Comment by zhangdh24** [comment]
./setup_injection.sh 64 HT20 

sudo echo 0x4101 |sudo tee /sys/kernel/debug/ieee80211/phy0/iwlwifi/iwldvm/debug/monitor_tx_rate 
 
sudo ./random_packets 1000 100 1 1000 




I use the code above on transmitter to configure the injection mode

------------------
Dongheng Zhang 
School of Electronic Engineering
University of Electronic Science and Technology of China


 




------------------ 原始邮件 ------------------
发件人: "John Gao";<notifications@github.com>;
发送时间: 2017年12月14日(星期四) 下午3:14
收件人: "dhalperi/linux-80211n-csitool-supplementary"<linux-80211n-csitool-supplementary@noreply.github.com>;
抄送: "Dongheng Zhang"<zhangdh24@foxmail.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [dhalperi/linux-80211n-csitool-supplementary] relative phase isnot right? (#124)



Unlucky, I also met this problem at 5 GHz, but it changes not that fast.
 There is a pi/2 phase shift after several seconds. Could you tell me the
 specific configuration of your platform？
 Many thanks.

**Comment by egaebel** [comment]
@zhangdh24 the performance reported in my paper is so different because I was running SpotFi from a single access point instead of 3+.

**Comment by zhangdh24** [comment]
@egaebel  I am afraid that it may not be the only reason. With a single access point, you can't realize the same localization accuracy as SpotFi. However, the accuracy of AOA estimation should be comparable. However, I have tested your data and the performance seems not to be as good as Fig. 8 in SpotFi. Thanks a lot for sharing your code, it is really impressive and helps me a lot.

**Comment by zhangdh24** [comment]
@egaebel @saltdou You can download the code of SpotFi on 
   https://bitbucket.org/mkotaru/spotfimusicaoaestimation
SpotFi uses although the method presented in ArrayTrack to correct
the phase.

**Comment by saltdou** [comment]
Thanks for your sharing.

**Comment by egaebel** [comment]
@zhangdh24 thanks for sharing! I wish they had released it earlier.

**Comment by dindokk** [comment]
@zhangdh24 can l get you email?

**Comment by dindokk** [comment]
@egaebel please l need your email
