### ISSUE TITLE
Using injection scripts.  FATAL: Module iwlwifi is in use.

### ISSUE THREAD

**Issue by xingchenzhang** [dhalperi/linux-80211n-csitool-supplementary#127]
Hi Guys,

I am trying to use machine with 5300 card as both transmitter and receiver, and using injection scripts.
However, when I try to run: ./setup_inject.sh 64 HT20, it says 'FATAL: Module iwlwifi is in use'. Is this normal?

Regards

**Comment by dpward** [comment]
That script tries to unload and then re-load the driver. On distributions other than Ubuntu, the 'iwldvm' module has to be unloaded before the 'iwlwifi' module is unloaded. (Ubuntu ships with a modprobe alias to do this.) You may want to edit the script as necessary for your purposes.

**Comment by xingchenzhang** [comment]
Thank you very much for your answer. I will as you suggested

**Comment by lidongning** [comment]
my pc is ubuntu12.04  ,when I run: ./setup_inject.sh 64 HT20,  I also "FATAL: Module iwlwifi is in use" , I don't understand it .  how to edit it ?  @dhalperi

**Comment by lidongning** [comment]
my pc is ubuntu12.04 ,when I run: ./setup_inject.sh 64 HT20, I also "FATAL: Module iwlwifi is in use" , I don't understand it . how to edit it ? @dhalperi  @star90
