### ISSUE TITLE
Which 30 subcarriers reported?

### ISSUE THREAD

**Issue by eric11220** [dhalperi/linux-80211n-csitool-supplementary#130]
If I understand correctly, there are 64 OFDM subcarriers in 802.11n or so protocols.
And the tool reports back 30 of them, so my question is which 30 subcarriers are reported back?

Thanks in advance!

**Comment by dpward** [comment]
Please see [FAQ 6](http://dhalperi.github.io/linux-80211n-csitool/faq.html).
