### ISSUE TITLE
Reported CSI subcarrier index order

### ISSUE THREAD

**Issue by eric11220** [dhalperi/linux-80211n-csitool-supplementary#134]
Of each pair of tx-rx, we obtain 30 complex numbers each time frame.
The subcarriers reported are [-28:2:-2,-1,1,3:2:27,28].

My question is do I need to perform fftshift on the received values to sort the subcarriers from lowest to highest frequency? 

That is, is the received indices [-28:2:-2,-1,1,3:2:27,28] or [1,3:2:27,28, -28:2:-2,-1] ?

**Comment by dhalperi** [comment]
they're in the order specified by the standard. I believe that's the first one.
