### ISSUE TITLE
Using access points that do not support 802.11n

### ISSUE THREAD

**Issue by rupamk** [dhalperi/linux-80211n-csitool-supplementary#136]
Hi I have installed the 'linux csi tool' and I have successfully collected the csi values using an access point( that supports 802.11 n). Can the linux-csi-tool be configured to work with any access point(for a/b/g)? If yes, what major modifications it requires?

**Comment by dhalperi** [comment]
No, sorry. The CSI measurements are only available for 802.11n packets. Please read [FAQ number 5](http://dhalperi.github.io/linux-80211n-csitool/faq.html).
