### ISSUE TITLE
Receiving from other access point or not?

### ISSUE THREAD

**Issue by rupamk** [dhalperi/linux-80211n-csitool-supplementary#138]
Thanks for the previous response. I have another issue to verify.

Regarding the received data the criteria is mentioned in FAQ 5. 
"
CSI is measured from a received packet under the following conditions:
1. The packet is transmitted using an 802.11n "HT" rate.
2. The receiver's logical configuration (e.g., channel type is HT, and channel width) and its physical configuration (e.g., correct number of antennas connected, all antennas work in the configured band, all antennas are enabled in the firmware) support the transmitted rate.
3. The receiver decodes the packet correctly, with no errors.

"

Currently I am connected to a commercial access point and I am receiving packets. But is it possible to receive data from a different access point that satisfies the above three criteria? 

Precisely, I want to verify that the packets that I am receiving should always be from the access point I am connected to or can be mixed up with packets(transmitted using an 802.11n "HT" rate) from other access points too?

**Comment by dhalperi** [comment]
You didn't copy the second half of the bullets, which answer your question:

> Client mode: The packet is transmitted by the connected AP, and the destination is either the local address or broadcast.

In client mode, you will only measure CSI for packets sent by the AP the client is connected to.
