### ISSUE TITLE
How to set the card to work in ad-hoc and monitor mode.

### ISSUE THREAD

**Issue by hot-dog** [dhalperi/linux-80211n-csitool-supplementary#139]
Hi.
I want my card to work in ad-hoc mode and monitor mode, but I have no idea how to set it. Can anyone just tell how to set it? Thanks!

**Comment by egaebel** [comment]
https://github.com/dhalperi/linux-80211n-csitool-supplementary/tree/master/injection

Read the code in the script files ./setup_monitor_csi.sh and    ./setup_inject.sh

**Comment by hot-dog** [comment]
Thanks, that's helpful, I get it.
