### ISSUE TITLE
size of csi

### ISSUE THREAD

**Issue by haimapi** [dhalperi/linux-80211n-csitool-supplementary#140]
dear all:

it confuses me that why the size of csi is different？ sometimes i got csi with size 1×3×30, while sometimes it's 2×3×30. they are all from one .dat file and the environment during collecting the csi is relatively stationary.   thx uuuuu

**Comment by dhalperi** [comment]
The transmitter is probably adapting rates between single-stream and multi-stream rates. Please read FAQ number 2: https://dhalperi.github.io/linux-80211n-csitool/faq.html
