### ISSUE TITLE
Get CSI from Beacon AP

### ISSUE THREAD

**Issue by paolo279** [dhalperi/linux-80211n-csitool-supplementary#145]
it's possible to take a csi from beacon of AP in monitor mode, without connect device to any AP ?
I'm able to get CSI both in Client and AP mode, but i ask you if it's possible to get CSI from beacons send from commercial 802.11n router. 

Sorry for my bad english, thanks !!

**Comment by dhalperi** [comment]
Please read [FAQ number 5](https://dhalperi.github.io/linux-80211n-csitool/faq.html). The answer is no because the requirements there are clearly not met.
