### ISSUE TITLE
sudo iwconfig wlan0 mode monitor 2>/dev/null 1>/dev/null  RETURN 250 ERROR CODE

### ISSUE THREAD

**Issue by Boeing738ng** [dhalperi/linux-80211n-csitool-supplementary#16]
When I set monitor, after I run **sudo iwconfig wlan0 mode monitor 2>/dev/null 1>/dev/null ** in commandline, then I echo $?, it return 250. But I have run command:
1. modprobe -r iwlwifi mac80211 cfg80211
2. modprobe iwlwifi connector_log=0x1
before it.
How to fix it?

**Comment by dhalperi** [comment]
Why don't you stop redirecting the output and actually report what it says?

**Comment by Boeing738ng** [comment]
Thank you for replying me first!
it outputted as these:


*Error for wireless request "Set Mode" (8B06)*
      *SET failed on device wlan0 ; device or resource busy.*

**Comment by dhalperi** [comment]
@dpward this is a problem you've seen before, right? AFAICT this did not happen in 10.04LTS

**Comment by dhalperi** [comment]
Is there a reason you can't use the four lines here, which loop until success? https://github.com/dhalperi/linux-80211n-csitool-supplementary/blob/master/injection/setup_monitor_csi.sh#L5

**Comment by Boeing738ng** [comment]
If I use while loop here, it will run forever.
