### ISSUE TITLE
Intel Corporation Centrino Wireless-N 1000 firmware

### ISSUE THREAD

**Issue by brunosoaresds** [dhalperi/linux-80211n-csitool-supplementary#161]
Hi all,

I'm trying to use the CSI tool with Intel Corporation Centrino Wireless-N 1000 card, however the firmware developed here is only from IWL 5300. It's possible to develop a firmware of CSI tool to other cards?

Best regards.,

**Comment by dhalperi** [comment]
No, this is clearly answered in the FAQ.
