### ISSUE TITLE
How to find out channel bandwidth?

### ISSUE THREAD

**Issue by awelkie** [dhalperi/linux-80211n-csitool-supplementary#168]
How can I determine the channel bandwidth for recorded data? For example, the data in 'matlab/sample_data' has three different values for the `rate` field: [0x100, 0x108, 0x110]. I'm assuming that this data is from a 20MHz channel because the [RATE_MCS_HT40_MSK](https://github.com/dhalperi/linux-80211n-csitool/blob/csitool-3.13/drivers/net/wireless/iwlwifi/dvm/commands.h#L309) bit flag is set to 0 in these values. Is this correct?

**Comment by asifhanif1122** [comment]
See this snapshot to get idea about settings while transmitting data in monitor mode.
![capture](https://cloud.githubusercontent.com/assets/15953476/15025444/b23ee5b4-1252-11e6-9b7c-bd56ce800a7c.PNG)

**Comment by dhalperi** [comment]
@awelkie yes -- this is right. You can also read the FAQ to confirm this.
