### ISSUE TITLE
Following the duplicated replies questions

### ISSUE THREAD

**Issue by jinzhang-unsw** [dhalperi/linux-80211n-csitool-supplementary#18]
After the short holiday I came back to see the last my question (the #4 issue) and your kind replies. I got the problem is 'Retransmissions can occur when CSMA/CA acknowledgments are not received.' Do you know why this always happens at every time? Does it cause by the router or the crowd environment?

**Comment by dhalperi** [comment]
It's almost certainly a problem with the way you have the devices set up. E.g., maybe the acknowledgements are being sent at too high a rate. Sorry, but this is something in your configuration and we are unlikely to be able to help.
