### ISSUE TITLE
process data error in MATLAB

### ISSUE THREAD

**Issue by zainalabidenakhtar** [dhalperi/linux-80211n-csitool-supplementary#183]
i am trying to process my .dat file in MATLAB but i get an error:
i write this command 

> > csi_trace = read_bf_file('sample_data/log.all_csi.6.7.6');
> > and get this error:
> > ??? Undefined function or method 'read_bfee' for input arguments of type 'uint8'.

Error in ==> read_bf_file at 66
        ret{count} = read_bfee(bytes);

can anybody help me in this regard

**Comment by tahmidzbr** [comment]
Hi can you please explain how you solved the problem?

**Comment by tfsanam** [comment]
How did you solve the problem?
