### ISSUE TITLE
2.4GHz or 5GHz is better

### ISSUE THREAD

**Issue by zainalabidenakhtar** [dhalperi/linux-80211n-csitool-supplementary#197]
some one can please guide me which frequency can give us better result, we should use 2.4GHz or 5GHz ? on which criteria we select these frequency bands?

**Comment by asifhanif1122** [comment]
Try to find a channel that is free of traffic. 2.4GHz band channels are usually congested and due to interference number of received packets also get reduced. So i will suggest to use channels in 5GHz band.

**Comment by zainalabidenakhtar** [comment]
@asifhanif1122 thanks for suggestion
