### ISSUE TITLE
AP Mode

### ISSUE THREAD

**Issue by ghost** [dhalperi/linux-80211n-csitool-supplementary#208]
Hi @dpward @dhalperi 

I have recently configured my Ubuntu workstation with Intel 5300 into the Access Point (AP).

I have connected my mobile phone to the AP and kept sending pings to the AP.

I started the "sudo linux-80211n-csitool-supplementary/netlink/log_to_file log.dat", **however no CSI was generated.**

I had Wireshark turned on at the same time and could clearly see the incoming and outgoing traffic (ping requests and replies).
dmesg | grep -i firmware:
`iwlwifi 0000:02:00.0: Loaded firmware version: 8.24.2.12 op_mode iwldvm` 
modinfo iwlwifi | head -n 1:
`/lib/modules/3.13.0-91-generic/updates/iwlwifi.ko`
Wireshark (MCS Information):
`Data Rate: 65.0 Mb/s` 

Do you have any ideas of why the CSI was not generated???

**Comment by tahmidzbr** [comment]
@Carll7 did you figure out why the CSI was not generated? I couldnt still figure mine. If you did can you please explain?
