### ISSUE TITLE
Does the csitools support ubuntu.14.04 well? 

### ISSUE THREAD

**Issue by gitbub1992** [dhalperi/linux-80211n-csitool-supplementary#21]

**Comment by dpward** [comment]
I have been able to install and test the CSI Tool driver/firmware on many recent versions of Ubuntu Linux (including 14.04 LTS) as well as Fedora Linux and Arch Linux.

**Comment by gitbub1992** [comment]
Appreciate！

**Comment by gitbub1992** [comment]
Much appreciate!
