### ISSUE TITLE
setting up Injection Mode

### ISSUE THREAD

**Issue by zainalabidenakhtar** [dhalperi/linux-80211n-csitool-supplementary#212]
I want to setup injection mode. I am following the injection script page: https://github.com/dhalperi/linux-80211n-csitool-supplementary/tree/master/injection

I started by making sure my wlan device is up by **using sudo ifconfig wlan0 up** then did the following:

```
 **sudo apt-get install libcap-dev** i found: Unable to fetch some archives, maybe run apt-get update. i try to run **apt-get update** i get error saying could not open lock file.
```

can anybody guide me how to get the Injection mode?

**Comment by tahmidzbr** [comment]
@zainalabidenakhtar Hi there. Can you please explain how you set it up?
