### ISSUE TITLE
can not log payload info to file using injection/monitor mode

### ISSUE THREAD

**Issue by liucc07** [dhalperi/linux-80211n-csitool-supplementary#222]
If I make the driver works in station mode and connect it to an AP with "connector_log=0x5" based on FAQ.12. It can successfully log both the payload and CSI into the file. 

However, if i set it work in monitor mode and another in inject mode, only the CSI is loged into the file. 

Can anyone help me figure it out?

**Comment by liucc07** [comment]
@dpward @dhalperi @ippeb

**Comment by swashah** [comment]
@liucc07 : will you mind sharing that how to log payload information? what modifications did you make in code. and also does setting 'connector_log=0x5' gives any packet sequence number or not?

**Comment by esoltana** [comment]
@liucc07 I have the same issue and I can not get the payload in any case with monitor/inject mode. Could you finally figure out any solution for this issue?
