### ISSUE TITLE
How to get ID number or source address in CSI packet?

### ISSUE THREAD

**Issue by ccjack** [dhalperi/linux-80211n-csitool-supplementary#246]
Hi, 
Is there any way to know the ID information or source address regarding the receiving packet's CSI? I have set up a linux-computer in AP-mode where there are 4 smartphone are connected. Then, the AP has receive a sequence of CSI from the four smartphone beacons even without pining them. However, it is hard to know each CSI belong to which smartphone. I have checked the cn_msg->id.val (in connector.h) which has always the same ID number even regarding different clients. Is there any way that I can know the present CSI belong to which clients (i.e smartphone)? Otherwise, I may need to use wireshark to map each CSI data with incoming packets. Any comments and suggestion will be appreciated! 

Status update: I saw that we can set the mask to the union of the information we would like to log. My next question is if we set the connector_log=0x5 or 0x7, will those additional information tell us source IP address? If so, where is the kernel file to tell us the log data format?   The iwl-agn-lib.c seems that it only show the IWL_CONN_BFEE_NOTIF_MSK data format. I have tried the 0x5 setup, the additional log data regarding IWL_CONN_RX_MPDU_MSK seems that it cannot be processed by using read_bfee.c tool since it is used for beam forming purpose.  

Thanks!

**Comment by ccjack** [comment]
I figure out how to do it. Thanks!

**Comment by asifhanif1122** [comment]
@ccjack Would you like to share method for identifying ID of clients?

**Comment by swashah** [comment]
@ccjack :Can you please briefly guide how can use sequence number of packets. Currently I have 02 laptops in monitor mode and third laptop is injecting packets. Now logically if 02 antennas are close enough then we will have similar CSI-amplitude. I am getting similar values but there is phase shift so can you please guide how can we use the sequence number to align signals?

**Comment by tahmidzbr** [comment]
@swashah Hi did you figure out how to get the sequence number of packets? If so can you please explain how. Many thanks.

**Comment by swashah** [comment]
@tahmidzbr : no i did'nt

**Comment by rednom** [comment]
@swashah @tahmidzbr Hi did you get how to get sequence number??
