### ISSUE TITLE
Why can't I get CSI at sometimes?

### ISSUE THREAD

**Issue by chensiwen** [dhalperi/linux-80211n-csitool-supplementary#249]
I have installed the CSI tool correctly and could get CSI data many times, but I can not get CSI data at sometimes. Why?

And I install it again, but the result  is as the attached files. Specially, I think the problem occurs firstly at the Step2 as follows:
chensiwen@chensiwen:~/linux-80211n-csitool$ git checkout ${CSITOOL_KERNEL_TAG}
**error: pathspec 'csitool-4.4' did not match any file(s) known to git.**
What is the 'csitool-4.4'? Is it related to my Linux version?

It's my system infomation that **"Linux version 4.4.0-45-generic (buildd@lgw01-30) (gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) ) #66~14.04.1-Ubuntu SMP Wed Oct 19 15:07:39 UTC 2016".**

![11](https://cloud.githubusercontent.com/assets/14833595/19723056/0690b880-9bac-11e6-8284-8b9cb8e18428.png)
![12](https://cloud.githubusercontent.com/assets/14833595/19723055/068b23c0-9bac-11e6-979e-f03ef25fbce8.png)

Please help me! @dpward @dhalperi @ippeb 
Thank you very much!

**Comment by chensiwen** [comment]
The problem is done. My Linux kernel is 4.4, so I change it to 4.2.

**Comment by arpapad** [comment]
Hi, how did you change your Linux Kernel?

**Comment by arpapad** [comment]
Hi, how did you change your Linux Kernel?
