### ISSUE TITLE
Dampening of signal at the subcarriers towards the end

### ISSUE THREAD

**Issue by avishekfsu** [dhalperi/linux-80211n-csitool-supplementary#28]
Hello, I have recently started working with the CSI tool, and I have noticed a dampening of the signal towards the edge subcarriers. Here is an example

![rss](https://cloud.githubusercontent.com/assets/9147635/6988060/7b40491a-da1b-11e4-97e3-cc5c4067478a.png)

In the figure above, the strength of the signal always goes down towards the end subcarriers. I have seen this in tests I ran at other locations as well, but have not been able to find out why this is happening. Am I doing something wrong with my configuration? 

FYI, the figure above is from 1X3 SIMO link with the rate set at 54Mbps.

**Comment by dhalperi** [comment]
You are correct; this effect is a result of the hardware's processing and we have to deal with it :)

**Comment by avishekfsu** [comment]
Thank you very much for your prompt reply. If possible, can you share with me how to handle this edge effect, i.e., reverting the CSI of the edge subcarriers back to their values without the additional change caused by the hardware, because the actual wireless channel should not always be weaker near the edges of the spectrum?

**Comment by dhalperi** [comment]
I have never compensated for it.

**Comment by avishekfsu** [comment]
OK, I'll have to think of some way to deal with this. Thank you so much for your help !
