### ISSUE TITLE
router set 40MHz BW but rate of CSI log is 20 Mhz BW

### ISSUE THREAD

**Issue by KeNopphon** [dhalperi/linux-80211n-csitool-supplementary#286]
Dear all,
I just start playing with CSI 802.11 tool and rate from CSI log confused me.
Basically, I set the router to operate at 40 MHz BW.  To confirm the setting, I checked  by 

'sudo iw wlan0 link' and I got
tx bitrate: 135 MBit/s MCS 7 40Mhz 
or
tx bitrate: 300 MBit/s MCS 15 40Mhz short GI 

But when I checked the received CSI log, I found that the rate is 271(0x10F) or 8463(0x210F) which, based on my understanding from http://dhalperi.github.io/linux-80211n-csitool/faq.html#faqrate , correspond to 20 Mhz BW (bit 11 = 0).

So my question is whether CSI log was recorded with 20 or 40 Mhz BW? 
and if it is 20 MHz, what should I change so that the rate from CSI log will be stated as 40 MHz BW
(bit 11 = 1).

Thank you in advance

**Comment by dhalperi** [comment]
See FAQ and 802.11n spec. Just because it's in a 40MHz band, nothing compels the router to transmit only using 40MHz MCS. If the channel supports it, and there is enough traffic on the network, normal rate selection should eventually get the router to progress to sending using a 40MHz MCS.
