### ISSUE TITLE
why I cannot get csi when using injection mode

### ISSUE THREAD

**Issue by xiukey** [dhalperi/linux-80211n-csitool-supplementary#296]
I can get csi in AP mode and in monitor mode I can set the network interface correctly. However, when I use randomPacket shell the receiver cannot get csi. Could anyone help me with this problem? Many thanks!

**Comment by xiukey** [comment]
solved it. just forget up the wlan0

**Comment by TahsinaSanam** [comment]
@xiukey Can you tell me in detail how you solved it? For monitor mode, is it possible to use router as transmitter?
