### ISSUE TITLE
How to identify the exactly value of subcarrier frequency ?

### ISSUE THREAD

**Issue by forrestcn** [dhalperi/linux-80211n-csitool-supplementary#304]
Hi everyone, can I identity the  exactly value of subcarrier frequency from a sampled packet?

The information that I know are:
(a) Channel and its center frequency
(b) Subcarrier frequency spacing, which is 312.5kHz
(c) Work mode of AP, Bandwidth and Grouping value

Assume 
(a) BW = 20M and Ng=2, which means “Carriers for which matrices are sent”  are –28,–26,–24,–22,–20,–18,–16,–14,–12,–10,–8,–6,–4,–2,–1, 1,3,5,7,9,11,13,15,17,19,21,23,25,27,28 denoted as Index[]
(b) Channel=1 and its center frequency is 2412MHz.

My question is:
Where can I find the equation to calculate the exactly value of subcarrier frequency?
For k-th element in CSI packet, the following equations are right or not?
    subcarrier id = Index(k)
    subcarrier frequency = 2412MHz + (subcarrier id)*312.5KHz  

Any comments are appreciated! Thanks!

**Comment by dhalperi** [comment]
Please see FAQ number "6. Which subcarriers are measured?"

In order to successfully operate in this space you will need to be able to answer these types of questions independently.
