### ISSUE TITLE
How to connect the AP/router

### ISSUE THREAD

**Issue by tfsanam** [dhalperi/linux-80211n-csitool-supplementary#309]
Hi,

I have two question.

1.I am confused about how CSI tool is having information about the AP. HOw can I give/connect my NIC to the specific AP?

if anyone have clue or have experience, please share.

2. If I want to work with different frequency, like 2.4 GHz, 4.00 GHz and 5 GHz, how can I do that? how to incorporate the frequency information in the CSI tool?

Thanks in advance.

TfSanam

**Comment by tfsanam** [comment]
can anyone help me on step 5 this instruction:

"Connect to an 802.11n access point, by using (for example) the iw and iproute2 utilities"

howtodo that?

**Comment by 764398256** [comment]
请问你的问题解决吗，我有相似的问题请教你
