### ISSUE TITLE
Injection: transmitter and receiver can not work well.

### ISSUE THREAD

**Issue by KOBETRACY** [dhalperi/linux-80211n-csitool-supplementary#31]
I have set two devices with Intel 5300 NICs running Ubuntu 11.04 .They can work well when they are pinging the AP with no password and logging CSI.
In the past few days,I want to use Injection script.But the "receiver" can't log the data from the "transmitter".Their ifconfig and iwconfig are as followed:
transmitter:

ifconfig
eth0      Link encap:Ethernet  HWaddr 00:e0:20:1c:33:f5  
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

eth1      Link encap:Ethernet  HWaddr 00:e0:20:1c:33:f6  
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:16436  Metric:1
          RX packets:2 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:100 (100.0 B)  TX bytes:100 (100.0 B)

mon0      Link encap:UNSPEC  HWaddr 00-16-EA-5F-2A-0C-00-00-00-00-00-00-00-00-00-00  
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:57 errors:0 dropped:57 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:16306 (16.3 KB)  TX bytes:0 (0.0 B)

wlan0     Link encap:Ethernet  HWaddr 00:16:ea:5f:2a:0c  
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

iwconfig
wlan0     IEEE 802.11abgn  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   Tx-Power=15 dBm   
          Retry  long limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
          
lo        no wireless extensions.

mon0      IEEE 802.11abgn  Mode:Monitor  Frequency:5.32 GHz  Tx-Power=15 dBm   
          Retry  long limit:7   RTS thr:off   Fragment thr:off
          Power Management:off
          
eth0      no wireless extensions.

eth1      no wireless extensions.

receiver:

ifconfig
eth2      Link encap:Ethernet  HWaddr 00:e0:20:1c:8d:0b  
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:385 errors:0 dropped:0 overruns:0 frame:0
          TX packets:53 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:36076 (36.0 KB)  TX bytes:7814 (7.8 KB)

eth3      Link encap:Ethernet  HWaddr 00:e0:20:1c:8d:0c  
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:16436  Metric:1
          RX packets:2 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:100 (100.0 B)  TX bytes:100 (100.0 B)

wlan0     Link encap:UNSPEC  HWaddr 00-16-EA-5F-2A-25-00-00-00-00-00-00-00-00-00-00  
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

iwconfig
wlan0     IEEE 802.11abgn  Mode:Monitor  Frequency:5.32 GHz  Tx-Power=15 dBm   
          Retry  long limit:7   RTS thr:off   Fragment thr:off
          Power Management:off
          
lo        no wireless extensions.

eth2      no wireless extensions.

eth3      no wireless extensions.

I followed README and did all the things as it says.But the "receiver" can't log any date from the "transmitter". I have read the issue #11 and #12 ,and I can't find a way to solve it.Anything I failed?or some other reasons.THANK YOU.

the state of reciever:
root@tracy-desktop:/home/tracy/csitools/linux-80211n-csitool-supplementary/injection# ./setup_monitor_csi.sh 64 HT20
root@tracy-desktop:/home/tracy/csitools/linux-80211n-csitool-supplementary/injection# sudo /home/tracy/csitools/linux-80211n-csitool-supplementary/netlink/log_to_file 0409.dat
then,nothing happenned.

the state of transmitter:
root@tracy-desktop:/home/tracy/csitools/linux-80211n-csitool-supplementary/injection# ./setup_inject.sh 64 HT20
root@tracy-desktop:/home/tracy/csitools/linux-80211n-csitool-supplementary/injection# echo 0x4101 | sudo tee /sys/kernel/debug/ieee80211/phy0/iwlwifi/debug/monitor_tx_rate
0x4101
root@tracy-desktop:/home/tracy/csitools/linux-80211n-csitool-supplementary/injection# sudo ./random_packets 1 100 1
Generating packet payloads 
Initializing LORCON
Sending 1 packets of size 100 (. every thousand)
root@tracy-desktop:/home/tracy/csitools/linux-80211n-csitool-supplementary/injection# sudo ./random_packets 10000000 100 1
Generating packet payloads 
Initializing LORCON
Sending 10000000 packets of size 100 (. every thousand)
..................................................50k
..................................................100k
..................................................150k
..................................................200k
.......................................^Z
[1]+  Stopped                 sudo ./random_packets 10000000 100 1

**Comment by co12** [comment]
@KOBETRACY ， how do you solve the problem?

**Comment by XWKate** [comment]
@KOBETRACY ,could you please tell how you sovled it? I have the same problem now. 
<img width="585" alt="image" src="https://user-images.githubusercontent.com/28868179/31983713-07dd3f48-b991-11e7-9a1a-de18a565fad1.png">

**Comment by kerul31** [comment]
@88wx  @co12  Were you able to solve this issue? I am having the same problem.

**Comment by liecn** [comment]
@KOBETRACY @88wx @kerul31 @dpward @dhalperi 
Hello! So anyone solved this problem? I find all the issues but cannot find an answer. So strange! Thank you for helping me.
