### ISSUE TITLE
Issue with connecting to access point with Intel5300 card

### ISSUE THREAD

**Issue by skocharllge** [dhalperi/linux-80211n-csitool-supplementary#326]
Hi All,
1 .I am using humming board quad core with below kernel version
Linux linux 3.14.79-fslc-imx6-sr #1 SMP Tue Apr 4 01:56:00 UTC 2017 armv7l GNU/Linux.

2.I could compile the ko file and bring up the wlan1 interface shown below by loading the kernel driver
sudo modprobe iwlwifi connector_log=0x1

root@linux:/home/debian# ifconfig
eth0      Link encap:Ethernet  HWaddr d0:63:b4:00:ec:0a  
          inet addr:192.168.0.126  Bcast:192.168.0.255  Mask:255.255.255.0
          inet6 addr: fe80::d263:b4ff:fe00:ec0a/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST DYNAMIC  MTU:1500  Metric:1
          RX packets:3428 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2395 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:3294436 (3.1 MiB)  TX bytes:308081 (300.8 KiB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:488 errors:0 dropped:0 overruns:0 frame:0
          TX packets:488 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:43848 (42.8 KiB)  TX bytes:43848 (42.8 KiB)

wlan1     Link encap:Ethernet  HWaddr 00:21:6a:2b:c7:c0  
          inet6 addr: fe80::221:6aff:fe2b:c7c0/64 Scope:Link
          UP BROADCAST MULTICAST DYNAMIC  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 

3.When I try to connect to access point ,I get connected message as shown below
 root@linux:/home/debian# iw wlan1 connect -w dlink-F2A4
wlan1 (phy #1): connected to f8:e9:03:c1:f2:a4

4.The state of link shows not connected.
root@linux:/home/debian# iw dev wlan1 link
Not connected.

how can we fix this issue so that it connects to access point?

BR
Sri

**Comment by skocharllge** [comment]
Hi All,

I could bring up the humming board with debian8.I do get the CSI data with connector_log =0x5 but not with connector_log =0x1.I am closing the issue as of now as its not very relevant.

If any one has clue on connector_log = 0x1 ,Please let me know.

**Comment by cbird7786** [comment]
Hi @skocharllge could you leave an email contact? I have similar problems you had, can we have a discussion ?

**Comment by skocharllge** [comment]
srinuk@gmail.com
