### ISSUE TITLE
A question about CSI packets

### ISSUE THREAD

**Issue by KOBETRACY** [dhalperi/linux-80211n-csitool-supplementary#37]
Dear Daniel , I used one transmitter and three receivers to bulid a system .I sent 100 packets , then different receiver received  packets in different nember.Maybe 100 ,98,or 99. I just want to know whether it is normal?If I used point-to-point ,the receiving packets  number is always100.Could you tell me something about that?Thank you !

**Comment by dhalperi** [comment]
Of course this is normal – wireless links are not perfect, and there can be interference, etc!

**Comment by KOBETRACY** [comment]
Thank you
