### ISSUE TITLE
can't read private key

### ISSUE THREAD

**Issue by zwlovefish** [dhalperi/linux-80211n-csitool-supplementary#375]
hello,everybody 
when I key in sudo make -C /lib/modules/$(uname -r)/build M=$(pwd)/drivers/net/wireless/iwlwifi INSTALL_MOD_DIR=updates \
    modules_install
it really shows "can't read private key" as the Installation Instructions said
how can i do?
this drives me mad!!!
please help me.
thank you very much

**Comment by smallsmart1994** [comment]
it doesn't matter, continue to execute is OK.

**Comment by zwlovefish** [comment]
ok，thank you！



------------------ 原始邮件 ------------------
发件人: "smallsmart1994"<notifications@github.com>;
发送时间: 2018年5月8日(星期二) 晚上10:50
收件人: "dhalperi/linux-80211n-csitool-supplementary"<linux-80211n-csitool-supplementary@noreply.github.com>;
抄送: "chinawolf"<1149610059@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [dhalperi/linux-80211n-csitool-supplementary] can't read privatekey (#375)




it doesn't matter, continue to execute is OK.
