### ISSUE TITLE
How to know which channel is used

### ISSUE THREAD

**Issue by KOBETRACY** [dhalperi/linux-80211n-csitool-supplementary#38]
Dear Daniel, now I can successfully receive the CSI packets, but I want to caculate the centre frequency     by using the channel number. In 'setup_inject.sh' ,it has set 'chn=64' .Which channel does the number '64' stand for? The 802.11n standard indicated there are 13 channels in the 2.4 GHz Band, how to choose the other channel by using the parament 'chn'?
Could you tell me something about that?Thank you !

**Comment by dhalperi** [comment]
64 is a channel. Please read more about the channels available for use in 802.11n!
