### ISSUE TITLE
Failed Installation?- solved

### ISSUE THREAD

**Issue by Greasyjoe** [dhalperi/linux-80211n-csitool-supplementary#399]
I just making sure I understand this portion.

"Connect to an 802.11n access point, by using (for example) the iw and iproute2 utilities (or if NetworkManager is enabled for the wireless interface, using nm-cli or the graphical applet)."

Does this mean connect to my router? My router has an option to be put into AP mode. Should I do that or is regular router mode OK? 

After running the final step
`sudo modprobe iwlwifi connector_log=0x1`

Should I be able to connect? It tries but never actually connects. Is there a way I can verify that the above step has be successful? 

I also have build errors....

```
make: Entering directory `/home/mld/linux-80211n-csitool-supplementary/netlink'
gcc -Wall -Werror    print_packets.c  -lm -o print_packets
gcc -Wall -Werror    get_first_bfee.c  -lm -o get_first_bfee
gcc -Wall -Werror    parse_log.c  -lm -o parse_log
echo "#undef CN_NETLINK_USERS" > connector_users.h
grep "#define CN_NETLINK_USERS" /lib/modules/4.2.0-040200-generic/build/include/uapi/linux/connector.h >> connector_users.h
gcc -Wall -Werror    log_to_file.c  -lm -o log_to_file
gcc -Wall -Werror   -c -o bf_to_eff.o bf_to_eff.c
gcc -Wall -Werror   -c -o iwl_nl.o iwl_nl.c
gcc -Wall -Werror   -c -o util.o util.c
gcc -Wall -Werror   -c -o q_approx.o q_approx.c
gcc -Wall -Werror    nl_bf_to_eff.c bf_to_eff.o iwl_nl.o util.o q_approx.o  -lm -o nl_bf_to_eff
```

But if I build it again...
```

make: Entering directory `/home/mld/linux-80211n-csitool-supplementary/netlink'
make: Nothing to be done for `all'.
```

Thank you for any help in advance.

**Comment by Greasyjoe** [comment]
I had the right kernal version, but the wrong OS, 14.04.5 =/= 14.04.4

**Comment by yinchengjin** [comment]
@Greasyjoe 
 Has your problem been solved?

**Comment by yinchengjin** [comment]
How do you resolve it? I have tried many times? But the problem is also? Can you give me some suggestions?

**Comment by Greasyjoe** [comment]
So after installing the firmware using 
`sudo modprobe iwlwifi connector_log=0x1`

you should be able to connect to your router if all security settings are off. I had mistakenly installed Ubuntu 14.04.5 instead of 14.04.4. When I reinstalled I instead used [12.04.5-i386](http://releases.ubuntu.com/12.04.5/ubuntu-12.04.5-desktop-i386.iso), and everything worked as expected.

**Comment by bigatl22** [comment]
@Greasyjoe

I'm getting the same build errors. Can you clarify if those went away completely when you switched to  12.04.5-i386? I am using 14.04.4 but I'm wondering if it matters if I use i386 or 64 bit.
