### ISSUE TITLE
Cannot get 3X3X30 CSI by using 3-antenna AP

### ISSUE THREAD

**Issue by angli19** [dhalperi/linux-80211n-csitool-supplementary#418]
I have used a TP-Link with 3 antenna as AP, a laptop with Intel 5300 as client. After following installation guide, I can only get 1X3X30 CSI matrix.  And if I use 0x1c910 to set transmitter rate of AP through my laptop, I cannot ping the AP. So how should I set to get 3X3X30 CSI matrix?

**Comment by steven520142** [comment]
I have the same problem. Sometimes I receive 1x3x30 CSI matrix but sometimes I receive 2x3x30 CSI matrix. Does someone know what's going on?

**Comment by angli19** [comment]
According to FAQ#2, we need to set some parameters on Tx through client (Rx). But the problem is I cannot ping the AP if I set them. Do you try this method?

**Comment by angli19** [comment]
To solve this problem, you can use external antenna.

**Comment by chenlk000** [comment]
I meet this problem too, setting for parameters is not work for me, just get 1x3x30 and 2x3x30. So I set another 5300 in inject mode and receive the csi in monitor mode, after setting parameters shows in FAQ#2 then I got 3x3x30 csi matrix sucessfully.
