### ISSUE TITLE
how can I get the RSS of every subcarriers?

### ISSUE THREAD

**Issue by gitbub1992** [dhalperi/linux-80211n-csitool-supplementary#42]
Dear dhalperi:
         I am confused about how to calculate the RSS of ervery subcarriers,the matlab function get_scaled_csi.m has calculate the CSI including the noise. Can you give me some advice on it? Does removing the noise directly work?
        Thanks!

**Comment by gitbub1992** [comment]
@dpward @dhalperi

**Comment by dhalperi** [comment]
Yes, you should be able to just set the `total_noise_power` to 1. https://github.com/dhalperi/linux-80211n-csitool-supplementary/blob/master/matlab/get_scaled_csi.m#L40

Please make sure you read carefully enough to understand why.

**Comment by gitbub1992** [comment]
@dhalperi   much appreciation!
