### ISSUE TITLE
How to use only one antenna to tx

### ISSUE THREAD

**Issue by garfield-lee** [dhalperi/linux-80211n-csitool-supplementary#43]
Dear Daniel,I'm using AP mode instead of injection script.And according to #34,I can set rx antenna numbers by editing file 'rx_chain_msk'.But there is no 'tx_chain_msk'.So I wonder how to use only one antenna to tx.
Thanks
Best wishes!

**Comment by dhalperi** [comment]
Please see FAQ#1, which explains how to set transmit rates and antennas.
