### ISSUE TITLE
the tmp.dat file is empty, and cannot get the csi data

### ISSUE THREAD

**Issue by hsm9028** [dhalperi/linux-80211n-csitool-supplementary#47]
Dear sir, I have carefully install the csi tool step by step in the old installation instructions, and each step has achieved the expectant result. However, in the last "let's try it out" phase, the tmp.dat file is always empty, and there isn't any data in it. I have a router without password, and has set it in the mode of 802.11n, HT. Whereas, the computer which embedded an intel 5300 NIC is a DELL desktop computer. In China, we have a group fellows who also face the same question, his tutor has used the csi tool in the desktop, and there isn't any data either. So I want to know is this the main problem in collecting the csi data? I'm looking forward to your answer. Thank you very much!

**Comment by dhalperi** [comment]
You need to use 802.11n rates. Please re-read the FAQ.

1. Do you have the pings being received by both endpoints successfully?
2. Are the packets being transmitted using 802.11n HT rates?
3. Did you install the correct firmware?
4. Did you load the driver with the correct flags?

etc.
