### ISSUE TITLE
db

### ISSUE THREAD

**Issue by TadiGuy** [dhalperi/linux-80211n-csitool-supplementary#48]
I'm using Octave to plot the sample CSI data included in the tool following the direction in the FAQ. I get an error that the db function is not implemented in Octave (I'm using Octave 4.0.0 on Windows). 

Is db(X) equivalent to 20\*log10(x) and db(X, 'pow') equivalent to 10\*log10(X) in the scripts? That's the assumption I made but my SNR values are shifted low by 26 in comparison to the sample plot in the FAQ.

**Comment by dpward** [comment]
Not only is that the correct conversion, I get the same plot as you using MATLAB R2015a on 64-bit Linux &mdash everything is shifted down by 26 dB.

@dhalperi I assume this is the result of some change to the MATLAB scripts after that plot was added to the FAQ. (I've only made one minor change to the MEX-file that wouldn't affect this.) Is this new result correct and should we just update the plot, or is this worth looking into further?

**Comment by dpward** [comment]
@dhalperi The commit that caused the plot to change is:
02af39e matlab: add quantization error to get_scaled_csi

**Comment by dhalperi** [comment]
Sure, that makes sense; the quantization error affects mostly very strong links, and I'm sure I didn't update the image after that change. Feel free to submit a new image.

**Comment by dpward** [comment]
What about this text in the FAQ below that plot:

> [...] we can see that all subcarriers are stronger than 40 dB, so the frequency-selective fading should cause few errors even using the highest rate. There is so little error, in fact, that MATLAB's error functions can't distinguish it from zero, and the SNR is effectively infinite.

Now the lower bound is actually 15 dB instead of 40 dB. I don't think that statement is true any more, right? (I'm actually referring to the plots in [your dissertation](http://arxiv.org/pdf/1301.6644.pdf) here.)

**Comment by dhalperi** [comment]
Yeah that text should probably get updated. I'm on mobile right now, but can take a look later. (Also feel free to update the text yourself...)

Thanks, I appreciate it.

**Comment by dpward** [comment]
@TadiGuy Also for future reference, the [signal package for Octave](http://wiki.octave.org/Signal_package) contains the db() function that you were missing.

**Comment by dpward** [comment]
Sorry I totally misread that page &mdash; which actually says that the db() function is *not* yet implemented in Octave.

**Comment by TadiGuy** [comment]
Thanks a lot.
