### ISSUE TITLE
Ping one time, get one CSI Packet?

### ISSUE THREAD

**Issue by lidongmeng** [dhalperi/linux-80211n-csitool-supplementary#49]
When I ping the ap , sometimes I got many packets of csi, but sometimes I only get one packet or none, is it normal? ( I think that I ping one time, I should get one csi packet,  am I right?)

**Comment by dpward** [comment]
A CSI sample is obtained for every packet you *receive* at a High-Throughput rate.
* Is there other traffic aside from the ICMP echo (ping) replies? Don't forget about ARP/Neighbor Discovery, Zeroconf, broadcast traffic from other nodes, etc.
* Are all of your incoming packets at HT rates?

If you want to understand what your incoming traffic looks like, you should add a second interface for the Intel adapter that is in monitor mode:
```
sudo iw phy phy0 interface add mon0 type monitor
sudo ip link set mon0 up
```
and then use Wireshark to capture on this interface (`mon0`). Take some time to examine the packet captures and understand what the traffic looks like from the AP. You should examine the MCS of the incoming packets to determine if an HT rate was used (and if CSI was collected).
