### ISSUE TITLE
Ping 100 time get more than 100 CSI packets ? why?

### ISSUE THREAD

**Issue by xuekevin** [dhalperi/linux-80211n-csitool-supplementary#50]
When I ping the ap , most time I got many packets of csi  which the number is bigger than the times I ping? I want know the reason, I use wireshark to moniter, almost all the incoming traffic is  ICMP echo (ping) replies, Only there is  DNS、TCP、 HTTP replies. I have read this answer.:https://github.com/dhalperi/linux-80211n-csitool-supplementary/issues/49
I didn't understand "You should examine the MCS of the incoming packets to determine if an HT rate was used (and if CSI was collected)" what‘s meaning of this sentence? thanks!

**Comment by dhalperi** [comment]
> When I ping the ap , most time I got many packets of csi which the number is bigger than the times I ping?

At least two possibilities:

1. 802.11 retries – the receiver measured the packet, but the transmitter did not receive the ack.
2. There is more going on than just pinging, e.g., web traffic or bonjour/avahi, etc.

> I want know the reason, I use wireshark to moniter, almost all the incoming traffic is ICMP echo (ping) replies, Only there is DNS、TCP、 HTTP replies.

Yeah, so if you're just pinging the AP it would be unlikely that you would see DNS or TCP or HTTP packets. You must have more traffic on your computer, which would easily explain why you're seeing more reports than the number of pings! A ping should show up in the logs as ICMP.

> I have read this answer.:#49
> I didn't understand "You should examine the MCS of the incoming packets to determine if an HT rate was used (and if CSI was collected)" what‘s meaning of this sentence? thanks!

Please read FAQ#2 and you will learn what MCS means, etc.
