### ISSUE TITLE
How to disable  5GHz on intel 5300?

### ISSUE THREAD

**Issue by gitbub1992** [dhalperi/linux-80211n-csitool-supplementary#55]
Dear Daniel：
       I have many APs with the same essid (different MAC address)，while half of that work on 2.4Ghz,another half work on 5Ghz.My problem is that my laptop with Intel 5300 always connect to the 5Ghz APs and can not connect to the 2.4Ghz ones,even I have assigned the MAC address.So how can   I disable 5Ghz on intel 5300?
     Thanks in advance.

**Comment by gitbub1992** [comment]
@dpward

**Comment by gitbub1992** [comment]
My problem have been solved after I changed the para of iwlwifi mod.So you can close this issue,thank you all the same.

**Comment by dhalperi** [comment]
Great!

**Comment by gitbub1992** [comment]
@dhalperi,new problem arises,I can not get CSI  anymore using log_to_file after I changed the para of iwlwifi .(the iwlwifi needed to be remod and reload),Will recompiling the iwlwifi and setting 5ghz_disable=1 work?Thanks you very much!

**Comment by dhalperi** [comment]
no idea, you're in uncharted territory here! Try it and let us know how it goes :)

**Comment by gitbub1992** [comment]
Thank you for your quick reply!!BTW, Where can I get The subcarrier index of CSI in 5Ghz?Since the total number of 5Ghz is 108.

**Comment by dhalperi** [comment]
I think you have some confusion – the number of subcarriers is not band-dependent. You can refer to the IEEE 802.11 standard for more information.... https://standards.ieee.org/getieee802/download/802.11-2012.pdf

**Comment by gitbub1992** [comment]
Sorry,I didn't correctly express my problems.My question is that  the corresponding subcarrier index sequence of  the 30 CFR exported by CSITools  in 5Ghz is the same with that of 2,4Ghz,which is [-28，-26，…，-4，-1，1，3，…，25，27，28]?

**Comment by gitbub1992** [comment]
The problem finally was solved by setting 5ghz_disable=1 in the file iwlwifi.conf under /etc/modprobe.d.If no file exists, create a new file,and Add a new line:options iwlwifi 5ghz_disable=1.
The refrence ：http://askubuntu.com/questions/419867/qualcomm-atheros-ar9485-wireless-network-adapter-not-working-on-ubuntu-13-10

**Comment by dhalperi** [comment]
Thanks for the update!

Yes, the sequence of subcarriers is the same for 20MHz channels independent of band.

**Comment by gitbub1992** [comment]
Much appreciation for your kind reply!!
