### ISSUE TITLE
On changing txpower using modified firmware

### ISSUE THREAD

**Issue by linkin8834** [dhalperi/linux-80211n-csitool-supplementary#61]
Hello,

Changing txpower only works with the original firmware. I can tune it from 0 dBm all the way to 15 dBm. However, given the modified one, whatever I change the txpower, it always stay at 15 dBm. Does the modified firmware prohibit txpower change? Thanks!

**Comment by dhalperi** [comment]
Yes, it is possible to change the tx power with the new firmware; this was a key part of my thesis.

**Comment by DontKnowMy** [comment]
Which one is the new firmware? And how can I change the txpower?

**Comment by DontKnowMy** [comment]
@dhalperi  could you please state how to lower the txpower using what new firmware? would be very appreciated. Thanks

**Comment by linkin8834** [comment]
@DontKnowMy No. With the firmware you are unable to set the transmit power. However, there are still many ways to do the experiment to tune the txpower:

1. Connect RF attenuators to the 5300 antennas on the TX side. If you want to control the receive sensitivity, connect RF attenuators to the 5300 antennas on the RX side.

2. Use another laptop with 5300 (or any other WiFi cards) in AP mode in Linux. Do not use modified firmware on that laptop, though. Then, just use iwconfig to change the txpower. I am able to tune to txpower to 0dBm with ease.

**Comment by Statisticss** [comment]
@dhalperi I read your thesis carefully and I found that in chapter 5.3, under 'Transmit Power Control', you said: 'I modified the driver and firmware to enable transmit power variation. With these changes, I can vary the transmit power level from -10dBm (100 uW) to +16dBm (40mW) in steps of 0.5 dB.' Could you plz give us some suggestion on how to do that? Thanks!
