### ISSUE TITLE
csi 2x3x30

### ISSUE THREAD

**Issue by FrancisTP** [dhalperi/linux-80211n-csitool-supplementary#62]
My csi is 2x3x30n instead of 1x3x30. Is this normal?

**Comment by lidongmeng** [comment]
@FrancisTP It is normal, the first param stands for the number of the transmitter antenna(here is 2), and the second is the number of the receiver antenna(here is 3).

**Comment by dhalperi** [comment]
Yes, this is normal. It means the transmitter sent 2 space-time-streams, aka a packet of MCS 8-15.
