### ISSUE TITLE
Question on correspondence between antenna on 5300 and CSI

### ISSUE THREAD

**Issue by linkin8834** [dhalperi/linux-80211n-csitool-supplementary#64]
Hello,
      The antenna ID on the chip follow the sequence of 1,3,2. Is antenna 1 equivalent to antenna a, antenna 2 to b, and 3 to c in the antenna mask setting for connected station rate configuration? In MATLAB, assuming one transmitting stream, is csi(1,1,:) corresponds to data from ant 1, csi(1,2,:) to ant 2, and csi(1,3,:) to ant 3 on the chip?
       Thanks!

**Comment by dpward** [comment]
Yes that's correct.

**Comment by linkin8834** [comment]
Thanks!
