### ISSUE TITLE
Can this tool be used in  Atheros AR9390 chipset ?

### ISSUE THREAD

**Issue by xietao992899** [dhalperi/linux-80211n-csitool-supplementary#66]
my lab is willing to use Atheros AR9390 chipset to get the csi data.It have been proved that your tools can be used in Intel 5300 chipset .But can this tool be used in  Atheros AR9390 chipset ?

**Comment by dhalperi** [comment]
Intel 5300 only.

**Comment by xietao992899** [comment]
then where can i get the instruction about AR9390 or is there any webpage or paper about this. It is really a very tough problem now.

**Comment by dhalperi** [comment]
Sorry, this project is only related to Intel 5300. You'll have to look elsewhere.

**Comment by YanMengSJTU** [comment]
@xietao992899 
Hi, you can refer to the site:  http://pdcc.ntu.edu.sg/wands/Atheros/
