### ISSUE TITLE
How to get received WiFi beacons from AP?

### ISSUE THREAD

**Issue by xuekevin** [dhalperi/linux-80211n-csitool-supplementary#69]
I read some papers, they proposed some system which disable active scanning, and only uses beacons from APs. I wonder how to get beacons message using your system? thanks!

**Comment by dhalperi** [comment]
FAQ number 5. You can only measure CSI for beacons from APs to which the CSI Tool is an associated client. There is at most 1 AP at a time in this implementation.

**Comment by xuekevin** [comment]
thanks!

**Comment by xuekevin** [comment]
Could you give me more tips ? I have read FAQ number 5, according to your answer, my understanding is I need to make the CSI Tool an associated client, what is associated client?   But how can I achieve that ?  What messages can I get from FAQ number 5 ?

**Comment by dhalperi** [comment]
You have clearly not followed the setup and installation instructions.

**Comment by xuekevin** [comment]
all right! I will review the instructions, thanks! :)
