### ISSUE TITLE
utilize CSI tool without ubuntu in ubiquitous device, can we get CSI information for smartphones supporting 802.11n

### ISSUE THREAD

**Issue by ersammah** [dhalperi/linux-80211n-csitool-supplementary#7]
need to use CSi information between two wifi devices on the human himself, the devices are needed to be small as possible, either smartphone or embedded wifi module. Implementation Idea is needed.

**Comment by dpward** [comment]
Please see [FAQ 4](http://dhalperi.github.io/linux-80211n-csitool/faq.html#others). This website is only for collecting CSI with the Intel Wi-Fi Link 5300 adapter (mini-PCIe), using custom firmware written for that adapter.
