### ISSUE TITLE
the received CSI values in a single subcarrier can fluctuate significantly? Is It normal?

### ISSUE THREAD

**Issue by xuekevin** [dhalperi/linux-80211n-csitool-supplementary#72]
I pick some samples in one location, I I draw the plot of one subcarrier's CSI value changes. As you can see. It changes significantly? @linkin8834 
 the x axis it the sample numbers,  I picked up about 120 packets. the y axis is the  module value of CSI message. I got these values by ping method.
![qq 20150703093709](https://cloud.githubusercontent.com/assets/7539866/8491124/1bbbba22-2167-11e5-8c53-f2021022d4bd.png)

what about your experiments? Is it similar with mine? if not, what tips you have followed? thanks a lot!

**Comment by linkin8834** [comment]
Hi Kevin,
   I take a look at mine. It seems to have much smaller fluctuations. My configuration is as follows: wireless router using two spatial streams, laptop using three receiving antennas. The ping interval is 0.01 sec. Is the access point always using fixed number of transmitting streams? My observation is that it sometimes change its number of spatial streams due to rate selection algorithm. On the other hand, Did you try injection and monitoring mode? That one is more stable.

**Comment by xuekevin** [comment]
@linkin8834 ，thanks a lot !  my AP also use two spatial streams and my laptop use three receiving antennas.  Most of the time I get 2*3*30 CSI packets, sometimes I can get 1*3*30 packets. the distance between laptop and AP is among 3-10 meters. our environment is lab room which has a lot 
computers, I put the laptop on a chair to pick up samples. all these has 
another questions is sometimes I can get CSI packets without ping, I use wireshark to capture the packets, some are ARP packets. have you met this condition? 
what's more, Have you tried to get CSI packets without ping, such as  get wifi beacons from ap?

**Comment by linkin8834** [comment]
@xuekevin No I did not try wireshark. If I use a laptop with hostapd as AP, and connect another laptop to it, I can pick up packages at the AP side when the client tries to associate with it. But, for wireless router as AP, I did not see any package coming in without **ping** it. I don't know if I can get the packages by beacon only. Most papers just said, 'beaconing is about 10Hz, so, we let the transmitter sends packages with 10 packages/sec (in injection mode).'. I guess that they are not actually use the beaconing to get the CSIs.

**Comment by xuekevin** [comment]
@linkin8834 ，thanks a lot! I think I need to do some work to make sure there are no packages coming without ping. and when I ping, I did not set ping interval as 0.01 sec. I don't know if it matters. let me try.
you answer help me a lot!

**Comment by xuekevin** [comment]
@linkin8834 I want to ask more about your wireless router, Have you made some setting?  the router I use  is TP-Link, I don't connect it with internet, I make some setting as follows.  Have you setup static ARP table? 
![qq 20150706113639](https://cloud.githubusercontent.com/assets/7539866/8515346/716d4ff8-23d3-11e5-81c7-09aa0d11771d.png)

I want to know what's wrong with my experients. hope you are a Chinese.

**Comment by linkin8834** [comment]
Hi Kevin,

    I did not setup the arp table. I set the static ip address as
192.168.1.1. Your settings are OKAY.

xuekevin <notifications@github.com>于2015年7月5日星期日写道：

> @linkin8834 <https://github.com/linkin8834> I want to ask more about your
> wireless router, Have you made some setting? the router I use is TP-Link, I
> don't connect it with internet, I make some setting as follows. Have you
> setup static ARP table?
> [image: qq 20150706113639]
> <https://cloud.githubusercontent.com/assets/7539866/8515346/716d4ff8-23d3-11e5-81c7-09aa0d11771d.png>
>
> I want to know what's wrong with my experients. hope you are a Chinese.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dhalperi/linux-80211n-csitool-supplementary/issues/72#issuecomment-118706245>
> .
>


-- 
CHEN CHEN
Electrical and Computer Engineering
University of Maryland, College Park
E-mail:linkin8834@gmail.com or cc8834@umd.edu
Address: KEB 2238, Kim Bldg

**Comment by linkin8834** [comment]
Hi Kevin,
   I suggest you try the injection and monitor mode with two laptops. That
should be more stable. Also, I choose channel 13 in the 2.4GHz for the
router.

Chen Chen <linkin8834@gmail.com>于2015年7月5日星期日写道：

> Hi Kevin,
>
>     I did not setup the arp table. I set the static ip address as
> 192.168.1.1. Your settings are OKAY.
>
> xuekevin <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> >于2015年7月5日星期日写道：
>
>> @linkin8834 <https://github.com/linkin8834> I want to ask more about
>> your wireless router, Have you made some setting? the router I use is
>> TP-Link, I don't connect it with internet, I make some setting as follows.
>> Have you setup static ARP table?
>> [image: qq 20150706113639]
>> <https://cloud.githubusercontent.com/assets/7539866/8515346/716d4ff8-23d3-11e5-81c7-09aa0d11771d.png>
>>
>> I want to know what's wrong with my experients. hope you are a Chinese.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/dhalperi/linux-80211n-csitool-supplementary/issues/72#issuecomment-118706245>
>> .
>>
>
>
> --
> CHEN CHEN
> Electrical and Computer Engineering
> University of Maryland, College Park
> E-mail:linkin8834@gmail.com
> <javascript:_e(%7B%7D,'cvml','E-mail:linkin8834@gmail.com');> or
> cc8834@umd.edu <javascript:_e(%7B%7D,'cvml','cc8834@umd.edu');>
> Address: KEB 2238, Kim Bldg
>
>

-- 
CHEN CHEN
Electrical and Computer Engineering
University of Maryland, College Park
E-mail:linkin8834@gmail.com or cc8834@umd.edu
Address: KEB 2238, Kim Bldg

**Comment by dpward** [comment]
@linkin8834 @xuekevin Packets do not have to be generated with the `ping` command. You can use other network control traffic, such as ARP or IPv6 Neighbor Discovery, or application traffic. The interval does not matter.

**Comment by linkin8834** [comment]
Hi David,
    Thanks for your suggestion. I was thinking that how fast you ping the AP would make it select a high data rate to turn on the 802.1n transmission...I have heard iperf a lot but have never tried that yet.

**Comment by dpward** [comment]
That's true, you could influence the rate control algorithm on a commercial AP. I would expect that along with the interval, increasing the size of the packets (with ping, using the `-s` option) would also have an effect.

**Comment by linkin8834** [comment]
Hi David,
     Thanks.

**Comment by xuekevin** [comment]
thanks a lot! @linkin8834  @dpward
