### ISSUE TITLE
How can I get CSI measurements on multiple links by capture beacon?

### ISSUE THREAD

**Issue by xuekevin** [dhalperi/linux-80211n-csitool-supplementary#75]
I have read FAQ 5 and 11, but I want make sure if my thought can work out. my thought is the aps can broadcast beacon frames periodically. my laptop can capture these frames without associate to the ap. because I  can get the namelist of the ap which is provided by the beacon frame. then if the beacon is tranmitted at HT rate, I can get CSI message from it. which can achieve the goal to connect muliple aps in client/ap mode. Is my thought correct? because I read some paper, they all mention beacon to get CSI message. but how? It make me confused.
In FAQ 11, you recommend to use injection mode for most multi-link measurements, which means I can use three laptop, two as transmitter, one as receiver, and one receiver can receive two transmitters' simultaneously. how does it happen? does it about beacon? thanks!!!

**Comment by dhalperi** [comment]
As in FAQ 5, the client must be connected to the AP. A client can only connect to a single AP at a time.

**Comment by xuekevin** [comment]
all right! I will try to injection mode the LORCON address does't work, can you give me another links? 
![qq 20150710121120](https://cloud.githubusercontent.com/assets/7539866/8612050/d88eeaee-26fc-11e5-9630-4c1d378f7cfe.png)

**Comment by xuekevin** [comment]
and you say the  injection mode can achieve most multi-link measurements. how does it happen? can you give me a brief explaination. It will save my day!

**Comment by xuekevin** [comment]
thanks! I have already downloaded LORCON!
