### ISSUE TITLE
Try injection mode encouter an error 

### ISSUE THREAD

**Issue by xuekevin** [dhalperi/linux-80211n-csitool-supplementary#76]
when I  excute ./setup_inject.sh 64 HT20, I encouter an error as follows. I have followed the tips. can you give me some advise what's wrong about my operation? 
"FATAL： Error inserting iwlwifi (lib/modules/3.5.0-23-generic/updates/iwlwifi.ko): Invalid argument"

**Comment by xuekevin** [comment]
@linkin8834,have you ever met this problem? thanks!

**Comment by linkin8834** [comment]
Hi Kevin,
     I think you are not correctly using the driver. Please execute the following 
     ls /lib/firmware/ | grep iwlwifi
     and let me know what's the results

**Comment by linkin8834** [comment]
Also, did you follow the instructions to build the modified firmware into your linux?

**Comment by xuekevin** [comment]
Here is the results
iwlwifi-1000-5.ucode
iwlwifi-100-5.ucode
iwlwifi-105-6.ucode
iwlwifi-135-6.ucode
iwlwifi-2000-6.ucode
iwlwifi-2030-6.ucode
iwlwifi-3945-2.ucode
iwlwifi-4965-2.ucode
iwlwifi-5000-2.ucode
iwlwifi-5000-2.ucode.sigcomm2010
iwlwifi-5000-5.ucode.orig
iwlwifi-5150-2.ucode
iwlwifi-6000-4.ucode
iwlwifi-6000g2a-5.ucode
iwlwifi-6000g2a-6.ucode
iwlwifi-6000g2b-6.ucode
iwlwifi-6050-5.ucode

**Comment by xuekevin** [comment]
I use the new installation instructions. my ubuntu is 12.04

**Comment by linkin8834** [comment]
Hi Kevin,
    I have not encountered this problem before. I am using ubuntu 14.04. But before that I was using 12.04 and it is working.

**Comment by xuekevin** [comment]
Is the results normal ? and what else should I do besides to follow tips as follows? could I miss some things?  thanks a lot! 
![temp](https://cloud.githubusercontent.com/assets/7539866/8642089/b2d925ce-2951-11e5-9a8e-77db86b14a57.png)
this step make install here, the directory is " linux-80211n-csitool-supplementary/injection/"  under this directory I just excute make order ,become make install can not work. Is the mormal?
![temp2](https://cloud.githubusercontent.com/assets/7539866/8642101/f49b9cb2-2951-11e5-92bd-e4d0e34e66b1.png)
by the way, could you give my your lorconv1 ? I want to make sure is not the library's problem.
my email is xuekaiwen_kevin@126.com

**Comment by xuekevin** [comment]
@dpward , 
Hi David! Have you ever met my problem？what kind of problem can it be?

**Comment by linkin8834** [comment]
Xue,
    Whats your email address? I can send you the lorcon code

xuekevin <notifications@github.com>于2015年7月12日星期日写道：

> Is the results normal ? and what else should I do besides to follow tips
> as follows? could I miss some things? thanks a lot!
> [image: temp]
> <https://cloud.githubusercontent.com/assets/7539866/8642089/b2d925ce-2951-11e5-9a8e-77db86b14a57.png>
> this step make install here, the directory is "
> linux-80211n-csitool-supplementary/injection/" under this directory I just
> excute make order ,become make install can not work. Is the mormal?
> [image: temp2]
> <https://cloud.githubusercontent.com/assets/7539866/8642101/f49b9cb2-2951-11e5-92bd-e4d0e34e66b1.png>
> by the way, could you give my your lorconv1 ? I want to make sure is not
> the library's problem.
> my email is xuekaiwen_kevin@126.com
> <javascript:_e(%7B%7D,'cvml','xuekaiwen_kevin@126.com');>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dhalperi/linux-80211n-csitool-supplementary/issues/76#issuecomment-120798086>
> .
>


-- 
CHEN CHEN
Electrical and Computer Engineering
University of Maryland, College Park
E-mail:linkin8834@gmail.com or cc8834@umd.edu
Address: KEB 2238, Kim Bldg

**Comment by xuekevin** [comment]
@linkin8834 , my email is xuekaiwen_kevin@126.com， you really help me a lot! thanks!

**Comment by co12** [comment]
@linkin8834 , can you also send me a copy of lorconv1? I can not download it, my email is xushxin1991@163.com. thanks a lot!

**Comment by xuekevin** [comment]
@linkin8834 @dpward  Sorry for asking again! I reinstall the ubuntu, when I try to git checkout the tag following instructions.
![4](https://cloud.githubusercontent.com/assets/7539866/8647029/16bf9c50-2987-11e5-8779-f15b6bd1c0c1.png)
I met an error as follows:
![2](https://cloud.githubusercontent.com/assets/7539866/8647034/22290e46-2987-11e5-83f8-98897af61a49.png)
the ${CSITOOL_KERNEL_TAG} is csitool-3.5 
Does it means the ubuntu version is not correct? Can you tell me what is your ubuntu version
My version is Ubuntu 12.04.2 LTS, the release version get by uname -r  is : 3.5.0-23-generic

**Comment by hmlsi** [comment]
Hi, I am also facing error but this is at very initial stage. when i tried to install libpcap-dev using sudo apt-get install libpcap-dev
It gave me some very long error list. The main thing was " Package octave is not configured yet". I have already installed octave 4.0.0 and its working fine. Can anybody please help me?

**Comment by linkin8834** [comment]
@co12  Sent. The 80211ninja which used to host the old lorcon code is down.

**Comment by linkin8834** [comment]
@xuekevin I am getting 3.16.0-30-generic as the kernel version.

**Comment by hmlsi** [comment]
@dpward  @linkin8834  can you please any help on this?

**Comment by dpward** [comment]
The issue is very likely that the script is trying to reload the iwlwifi module with the parameter `debug=0x40000` but the kernel (and the modified driver) were built with `CONFIG_IWLWIFI_DEBUG=n`. The quick workaround is remove that parameter from the script.

**Comment by ozawali** [comment]
@linkin8834  Hello, that I cannot download the  lorconv1 and can you send me this ? thank you!  my email is ozawa1314@gmail.com

**Comment by linkin8834** [comment]
@ozawali  Sent.

**Comment by ozawali** [comment]
@linkin8834   I don't know the  lorconv1 very well and what does this component function?

**Comment by linkin8834** [comment]
@ozawali  It is used in injection mode for the binary file random_packets.

**Comment by xuekevin** [comment]
@dpward thanks a lot ! you mean I should delete "modprobe iwlwifi debug = 0x40000", is that normal will It cause some other problems?

**Comment by xuekevin** [comment]
@linkin8834 , @dpward  except for the step below,what else should I take care, do I need to set the address which is descibed in FAQ5 "The packet is addressed both to and from a hardcoded, fixed address"?

**Comment by ozawali** [comment]
@linkin8834  Do I need install the libpcap-dev?

**Comment by linkin8834** [comment]
@ozawali I didn't remember. I think it was installed by default

**Comment by linkin8834** [comment]
@xuekevin  As far as I am concerned, I did not change that address.

**Comment by xuekevin** [comment]
@linkin8834 thanks! After I remove the debug=0x40000 it works!

**Comment by dhalperi** [comment]
Glad it's working!

**Comment by lixiaohai** [comment]
@linkin8834 Hello, that I cannot download the lorconv1 and could you send me this ? thank you! my email is lxh4217976@163.com

**Comment by linkin8834** [comment]
@lixiaohai  You can try this link: https://github.com/dhalperi/lorcon-old

**Comment by lixiaohai** [comment]
@linkin8834 I have downed it.Tks!
