### ISSUE TITLE
download LORCONv1 from http://802.11ninja.net/svn/lorcon/branch/lorcon-old/

### ISSUE THREAD

**Issue by hmlsi** [dhalperi/linux-80211n-csitool-supplementary#78]
This download link is not working.This is a continuous issue which almost everyone is facing. Can someone provide any alternative?

**Comment by ozawali** [comment]
you can download from the IEEE802.11

**Comment by dhalperi** [comment]
@hmlsi I sent a request to the authors of lorcon to see if they can post a new version of it. In the meantime, would anyone who has a working copy of lorcon-old care to put a mirror on github?

**Comment by dhalperi** [comment]
@ozawali I don't think that's correct.

**Comment by co12** [comment]
@hmlsi ， I don't know how to put a mirror on github, but I can send you a working copy by email

**Comment by linkin8834** [comment]
I notice that as well. I keep a local copy at my disk.

**Comment by hmlsi** [comment]
Thanks a lot all of you. My email id is hmlsi@yahoo.com

**Comment by co12** [comment]
@hmlsi Already sent, please check

**Comment by dhalperi** [comment]
If you send me a copy (daniel@halper.in) I will create a mirror on github and update the instructions. Thanks!

**Comment by dhalperi** [comment]
Mirror is up here: https://github.com/dhalperi/lorcon-old

**Comment by hmlsi** [comment]
Thank you all of you :)
