### ISSUE TITLE
How can I get the CSI information from multiple AP at the same time?

### ISSUE THREAD

**Issue by chenyongxi** [dhalperi/linux-80211n-csitool-supplementary#8]
Now, I can get the CSI information from the AP which I connected. However, I want get the CSI information from multiple AP at the same time. I see your FAQ answer 11. I did as he said. But I don't understand how to use it.   Who is receiver? Who is transmitter? How to use?

**Comment by chenyongxi** [comment]
Look forward to your reply, very grateful！

**Comment by dhalperi** [comment]
Say there are 5 devices in the network, A B C D and E. If you want to measure the CSI for links A->E, B->E, C->E, and D->E all at the same time, then ABCD are the transmitters and E is the receiver.

**Comment by chenyongxi** [comment]
See your reply I am very happy. Thankyou! But I did not completely understand. what are A,B,C,D? AP or notebook? if A,B,C,D are AP, how to operate them ？

**Comment by dhalperi** [comment]
A,B,C,D are transmitters from which you can inject packets to the broadcast address.

There is no way to listen to multiple commercial APs at once, as far as I know. Please read the FAQ again to understand why.

**Comment by chenyongxi** [comment]
Are you mean no way to get the CSI information from multiple APs at the same time?

**Comment by dhalperi** [comment]
Correct.

**Comment by chenyongxi** [comment]
Thank you very much! If I have a problem I have to ask you to come back.

**Comment by chenyongxi** [comment]
Excuse me,if I use injection mode,can I get the CSI information from multiple APs at the same time?
