### ISSUE TITLE
Why I think the three rssi value in the csi_entry Inaccurate？

### ISSUE THREAD

**Issue by chenyongxi** [dhalperi/linux-80211n-csitool-supplementary#83]
Why I think the three rssi value in the csi_entry Inaccurate？

**Comment by dhalperi** [comment]
Pardon?

**Comment by chenyongxi** [comment]
I get the CSI data int csi_entry, in the csi_entry has some other data , for example rssi_a,rssi_b ,but I think the rssi_a and rssi_b is id not accurate.

**Comment by dhalperi** [comment]
They are all accurate as reported by the NIC. As per many documents and code, they must be translated to dBm from the NIC's internal reference. https://github.com/dhalperi/linux-80211n-csitool-supplementary/blob/master/matlab/get_total_rss.m
