### ISSUE TITLE
Setting up transmitting rate for commercial AP

### ISSUE THREAD

**Issue by hmlsi** [dhalperi/linux-80211n-csitool-supplementary#85]
I have read FAQ#1. I am using commercially available TP link. using this as AP, can I set my rate?

**Comment by ozawali** [comment]
No , you must on the injection mode.

**Comment by dpward** [comment]
@ozawali injection mode is not required for setting the rate.

@hmlsi You can set the transmit rate from a client with an Intel 5300 adapter to a commercial AP (which doesn't provide CSI, as the AP is receiving). However you can't set the transmit rate on a commercial AP. You can set the rate though with an Intel 5300 adapter operating as an AP.

**Comment by hmlsi** [comment]
Got it. That means for setting transmit rate, transmitter must have Intel 5300. Thanks

**Comment by ozawali** [comment]
@dpward  I mean you can set the rate and the antennas of the transmitter  on the injection mode, but for the csi data  although you change the commercial ap rate but the rate of getting csi is not useful
