### ISSUE TITLE
Does this tool measure the instantaneous CSI?

### ISSUE THREAD

**Issue by ClarenceZSK** [dhalperi/linux-80211n-csitool-supplementary#87]
The CSI measurement must have noise. I would like to know the noise model. Is it a Gaussian? Would you please give me some advices to understand it or some related materials to read? Thanks a lot.

**Comment by ClarenceZSK** [comment]
In WiKI, the CSI measurement noise follow circular symmetric complex normal distribution. I would like to know that if the CSI tool here measures the instantaneous CSI. Thanks a lot for your help.

**Comment by dhalperi** [comment]
yes,
