### ISSUE TITLE
CSI rate

### ISSUE THREAD

**Issue by eric11220** [dhalperi/linux-80211n-csitool-supplementary#89]
Hi! Would like to ask if there's a way to control the rate the receiver gets CSI?

That is, is it able to ensure that the receiver will get approximately, say 500 csi samples per second?
I tried ping or scp a file and catch csi at the same time, but all they brought me is only up to around 300 per second.

Thanks!

**Comment by dhalperi** [comment]
strictly related to rate of received packets. Use short packets as possible with no aggregation.
