### ISSUE TITLE
Confuse about CSI

### ISSUE THREAD

**Issue by lidongmeng** [dhalperi/linux-80211n-csitool-supplementary#92]
I have a question about how CSI generates? Is it generated by the Intel 5300 NIC based on the protocol  of 802.11n? Then the kernel space get information from it and assembled them into a fixed format CSI, and send the CSI to the user space as we get in the log file? Am I right?

**Comment by dhalperi** [comment]
You have the gist correct, if a bit imprecise.

Please read http://www.halper.in/pubs/halperin_csitool.pdf and http://dhalperi.github.io/linux-80211n-csitool/faq.html thoroughly.
