### ISSUE TITLE
zeros reading in CSI.

### ISSUE THREAD

**Issue by jackyfff** [dhalperi/linux-80211n-csitool-supplementary#99]
Dear all,

I have successfully set up the CSI logging function and now am looking at the CSI files. One thing that bothers me is that why are there so many zeros reading in certain subcarriers? Especially, they appear one another. Do they have explanations?

Thanks,

**Comment by dhalperi** [comment]
Is the link very weak?

**Comment by jackyfff** [comment]
@dhalperi 
Actually no. The link is robust. Also I've used two routers in this configuration. Two links are like the same.

**Comment by dhalperi** [comment]
Closing outdated issue.
